package Negocio.Compras;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import Negocio.Deposito.Faltante;
import Negocio.Compras.Material;
import Negocio.Compras.OrdenCompra;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TDetallesOrdenCompra generated by hbm2java
 */
@Entity
@Table(name="T_DETALLES_ORDEN_COMPRA"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class DetalleOrdenCompra  implements java.io.Serializable {


     private int idDetalleOrdenCompra;
     private OrdenCompra TOrdenesCompra;
     private Material TMateriales;
     private short cantidadPedida;
     private short cantidadRecibida;
     private Set<Faltante> TFaltanteses = new HashSet<Faltante>(0);

    public DetalleOrdenCompra() {
    }

	
    public DetalleOrdenCompra(int idDetalleOrdenCompra, OrdenCompra TOrdenesCompra, short cantidadPedida, short cantidadRecibida) {
        this.idDetalleOrdenCompra = idDetalleOrdenCompra;
        this.TOrdenesCompra = TOrdenesCompra;
        this.cantidadPedida = cantidadPedida;
        this.cantidadRecibida = cantidadRecibida;
    }
    public DetalleOrdenCompra(int idDetalleOrdenCompra, OrdenCompra TOrdenesCompra, Material TMateriales, short cantidadPedida, short cantidadRecibida, Set<Faltante> TFaltanteses) {
       this.idDetalleOrdenCompra = idDetalleOrdenCompra;
       this.TOrdenesCompra = TOrdenesCompra;
       this.TMateriales = TMateriales;
       this.cantidadPedida = cantidadPedida;
       this.cantidadRecibida = cantidadRecibida;
       this.TFaltanteses = TFaltanteses;
    }
   
     @Id 
    
    @Column(name="ID_DETALLE_ORDEN_COMPRA", unique=true, nullable=false, precision=8, scale=0)
    public int getIdDetalleOrdenCompra() {
        return this.idDetalleOrdenCompra;
    }
    
    public void setIdDetalleOrdenCompra(int idDetalleOrdenCompra) {
        this.idDetalleOrdenCompra = idDetalleOrdenCompra;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ORDEN_COMPRA", nullable=false)
    public OrdenCompra getTOrdenesCompra() {
        return this.TOrdenesCompra;
    }
    
    public void setTOrdenesCompra(OrdenCompra TOrdenesCompra) {
        this.TOrdenesCompra = TOrdenesCompra;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_MATERIAL")
    public Material getTMateriales() {
        return this.TMateriales;
    }
    
    public void setTMateriales(Material TMateriales) {
        this.TMateriales = TMateriales;
    }
    
    @Column(name="CANTIDAD_PEDIDA", nullable=false, precision=3, scale=0)
    public short getCantidadPedida() {
        return this.cantidadPedida;
    }
    
    public void setCantidadPedida(short cantidadPedida) {
        this.cantidadPedida = cantidadPedida;
    }
    
    @Column(name="CANTIDAD_RECIBIDA", nullable=false, precision=3, scale=0)
    public short getCantidadRecibida() {
        return this.cantidadRecibida;
    }
    
    public void setCantidadRecibida(short cantidadRecibida) {
        this.cantidadRecibida = cantidadRecibida;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TDetallesOrdenCompra")
    public Set<Faltante> getTFaltanteses() {
        return this.TFaltanteses;
    }
    
    public void setTFaltanteses(Set<Faltante> TFaltanteses) {
        this.TFaltanteses = TFaltanteses;
    }




}


