package Negocio.Compras;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TEordenCompra generated by hbm2java
 */
@Entity
@Table(name="T_EORDEN_COMPRA"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class EstadoOrdenCompra  implements java.io.Serializable {


     private byte idEordenCompra;
     private String nombre;
     private String descripcion;
     private Set<OrdenCompra> TOrdenesCompras = new HashSet<OrdenCompra>(0);

    public EstadoOrdenCompra() {
    }

	
    public EstadoOrdenCompra(byte idEordenCompra, String nombre) {
        this.idEordenCompra = idEordenCompra;
        this.nombre = nombre;
    }
    public EstadoOrdenCompra(byte idEordenCompra, String nombre, String descripcion, Set<OrdenCompra> TOrdenesCompras) {
       this.idEordenCompra = idEordenCompra;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.TOrdenesCompras = TOrdenesCompras;
    }
   
     @Id 
    
    @Column(name="ID_EORDEN_COMPRA", unique=true, nullable=false, precision=2, scale=0)
    public byte getIdEordenCompra() {
        return this.idEordenCompra;
    }
    
    public void setIdEordenCompra(byte idEordenCompra) {
        this.idEordenCompra = idEordenCompra;
    }
    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="DESCRIPCION", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TEordenCompra")
    public Set<OrdenCompra> getTOrdenesCompras() {
        return this.TOrdenesCompras;
    }
    
    public void setTOrdenesCompras(Set<OrdenCompra> TOrdenesCompras) {
        this.TOrdenesCompras = TOrdenesCompras;
    }




}


