package Negocio.Compras;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TMaterialesXProveedor generated by hbm2java
 */
@Entity
@Table(name="T_MATERIALES_X_PROVEEDOR"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class MaterialesXProveedor  implements java.io.Serializable {


     private short idMaterialXProveedor;
     private Proveedor TProveedores;
     private Material TMateriales;

    public MaterialesXProveedor() {
    }

	
    public MaterialesXProveedor(short idMaterialXProveedor) {
        this.idMaterialXProveedor = idMaterialXProveedor;
    }
    public MaterialesXProveedor(short idMaterialXProveedor, Proveedor TProveedores, Material TMateriales) {
       this.idMaterialXProveedor = idMaterialXProveedor;
       this.TProveedores = TProveedores;
       this.TMateriales = TMateriales;
    }
   
     @Id 
    
    @Column(name="ID_MATERIAL_X_PROVEEDOR", unique=true, nullable=false, precision=3, scale=0)
    public short getIdMaterialXProveedor() {
        return this.idMaterialXProveedor;
    }
    
    public void setIdMaterialXProveedor(short idMaterialXProveedor) {
        this.idMaterialXProveedor = idMaterialXProveedor;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PROVEEDOR")
    public Proveedor getTProveedores() {
        return this.TProveedores;
    }
    
    public void setTProveedores(Proveedor TProveedores) {
        this.TProveedores = TProveedores;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_MATERIAL")
    public Material getTMateriales() {
        return this.TMateriales;
    }
    
    public void setTMateriales(Material TMateriales) {
        this.TMateriales = TMateriales;
    }




}


