package Negocio.Produccion;
// Generated 18/03/2012 17:10:18 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * THerramientasParticular generated by hbm2java
 */
@Entity
@Table(name="T_HERRAMIENTAS_PARTICULAR"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class HerramientaParticular  implements java.io.Serializable {


     private short idHerramientaParticular;
     private TipoHerramienta TTherramienta;
     private String caracteristicas;
     private String modelo;
     private String nombre;
     private String observaciones;
     private Date fecBaja;
     private String motivoBaja;
     private Set TMaqHerrPartXDetPlans = new HashSet(0);

    public HerramientaParticular() {
    }

	
    public HerramientaParticular(short idHerramientaParticular, TipoHerramienta TTherramienta, String caracteristicas, String modelo, String nombre) {
        this.idHerramientaParticular = idHerramientaParticular;
        this.TTherramienta = TTherramienta;
        this.caracteristicas = caracteristicas;
        this.modelo = modelo;
        this.nombre = nombre;
    }
    public HerramientaParticular(short idHerramientaParticular, TipoHerramienta TTherramienta, String caracteristicas, String modelo, String nombre, String observaciones, Date fecBaja, String motivoBaja, Set TMaqHerrPartXDetPlans) {
       this.idHerramientaParticular = idHerramientaParticular;
       this.TTherramienta = TTherramienta;
       this.caracteristicas = caracteristicas;
       this.modelo = modelo;
       this.nombre = nombre;
       this.observaciones = observaciones;
       this.fecBaja = fecBaja;
       this.motivoBaja = motivoBaja;
       this.TMaqHerrPartXDetPlans = TMaqHerrPartXDetPlans;
    }
   
     @Id 
    
    @Column(name="ID_HERRAMIENTA_PARTICULAR", unique=true, nullable=false, precision=3, scale=0)
    public short getIdHerramientaParticular() {
        return this.idHerramientaParticular;
    }
    
    public void setIdHerramientaParticular(short idHerramientaParticular) {
        this.idHerramientaParticular = idHerramientaParticular;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_THERRAMIENTA", nullable=false)
    public TipoHerramienta getTTherramienta() {
        return this.TTherramienta;
    }
    
    public void setTTherramienta(TipoHerramienta TTherramienta) {
        this.TTherramienta = TTherramienta;
    }
    
    @Column(name="CARACTERISTICAS", nullable=false, length=200)
    public String getCaracteristicas() {
        return this.caracteristicas;
    }
    
    public void setCaracteristicas(String caracteristicas) {
        this.caracteristicas = caracteristicas;
    }
    
    @Column(name="MODELO", nullable=false, length=50)
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="OBSERVACIONES", length=200)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_BAJA", length=23)
    public Date getFecBaja() {
        return this.fecBaja;
    }
    
    public void setFecBaja(Date fecBaja) {
        this.fecBaja = fecBaja;
    }
    
    @Column(name="MOTIVO_BAJA", length=50)
    public String getMotivoBaja() {
        return this.motivoBaja;
    }
    
    public void setMotivoBaja(String motivoBaja) {
        this.motivoBaja = motivoBaja;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="THerramientasParticular")
    public Set getTMaqHerrPartXDetPlans() {
        return this.TMaqHerrPartXDetPlans;
    }
    
    public void setTMaqHerrPartXDetPlans(Set TMaqHerrPartXDetPlans) {
        this.TMaqHerrPartXDetPlans = TMaqHerrPartXDetPlans;
    }




}


