package Negocio.GestionUsuario;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import Negocio.Administracion.Empleado;
import Negocio.Ventas.Cliente;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TUsuarios generated by hbm2java
 */
@Entity
@Table(name="T_USUARIOS"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String nombreUsuario;
     private String contrasenia;
     private Set<Empleado> TEmpleadoses = new HashSet<Empleado>(0);
     private Set<Cliente> TClienteses = new HashSet<Cliente>(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String nombreUsuario, String contrasenia) {
        this.idUsuario = idUsuario;
        this.nombreUsuario = nombreUsuario;
        this.contrasenia = contrasenia;
    }
    public Usuario(int idUsuario, String nombreUsuario, String contrasenia, Set<Empleado> TEmpleadoses, Set<Cliente> TClienteses) {
       this.idUsuario = idUsuario;
       this.nombreUsuario = nombreUsuario;
       this.contrasenia = contrasenia;
       this.TEmpleadoses = TEmpleadoses;
       this.TClienteses = TClienteses;
    }
   
     @Id 
    
    @Column(name="ID_USUARIO", unique=true, nullable=false, precision=5, scale=0)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    
    @Column(name="NOMBRE_USUARIO", nullable=false, length=50)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    
    @Column(name="CONTRASENIA", nullable=false, length=50)
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TUsuarios")
    public Set<Empleado> getTEmpleadoses() {
        return this.TEmpleadoses;
    }
    
    public void setTEmpleadoses(Set<Empleado> TEmpleadoses) {
        this.TEmpleadoses = TEmpleadoses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TUsuarios")
    public Set<Cliente> getTClienteses() {
        return this.TClienteses;
    }
    
    public void setTClienteses(Set<Cliente> TClienteses) {
        this.TClienteses = TClienteses;
    }




}


