package BaseDeDatos.Produccion;
// Generated 09/08/2011 13:12:12 by Hibernate Tools 3.2.1.GA


import BaseDeDatos.Produccion.TProductos;
import BaseDeDatos.Administracion.TCargos;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TEtapasProduccionEspecifica generated by hbm2java
 */
public class TEtapasProduccionEspecifica  implements java.io.Serializable {


     private int idEtapaProduccionEspecifica;
     private TCargos TCargos;
     private TEtapasProduccion TEtapasProduccion;
     private TProductos TProductos;
     private String descripcionEspecifica;
     private BigDecimal horasHombre;
     private byte numeroOrden;
     private Set TDetallesEtapas = new HashSet(0);
     private Set TTmaquinaHerramientas = new HashSet(0);
     private Set TDetallesPlans = new HashSet(0);

    public TEtapasProduccionEspecifica() {
    }

	
    public TEtapasProduccionEspecifica(int idEtapaProduccionEspecifica, TCargos TCargos, TEtapasProduccion TEtapasProduccion, TProductos TProductos, String descripcionEspecifica, BigDecimal horasHombre, byte numeroOrden) {
        this.idEtapaProduccionEspecifica = idEtapaProduccionEspecifica;
        this.TCargos = TCargos;
        this.TEtapasProduccion = TEtapasProduccion;
        this.TProductos = TProductos;
        this.descripcionEspecifica = descripcionEspecifica;
        this.horasHombre = horasHombre;
        this.numeroOrden = numeroOrden;
    }
    public TEtapasProduccionEspecifica(int idEtapaProduccionEspecifica, TCargos TCargos, TEtapasProduccion TEtapasProduccion, TProductos TProductos, String descripcionEspecifica, BigDecimal horasHombre, byte numeroOrden, Set TDetallesEtapas, Set TTmaquinaHerramientas, Set TDetallesPlans) {
       this.idEtapaProduccionEspecifica = idEtapaProduccionEspecifica;
       this.TCargos = TCargos;
       this.TEtapasProduccion = TEtapasProduccion;
       this.TProductos = TProductos;
       this.descripcionEspecifica = descripcionEspecifica;
       this.horasHombre = horasHombre;
       this.numeroOrden = numeroOrden;
       this.TDetallesEtapas = TDetallesEtapas;
       this.TTmaquinaHerramientas = TTmaquinaHerramientas;
       this.TDetallesPlans = TDetallesPlans;
    }
   
    public int getIdEtapaProduccionEspecifica() {
        return this.idEtapaProduccionEspecifica;
    }
    
    public void setIdEtapaProduccionEspecifica(int idEtapaProduccionEspecifica) {
        this.idEtapaProduccionEspecifica = idEtapaProduccionEspecifica;
    }
    public TCargos getTCargos() {
        return this.TCargos;
    }
    
    public void setTCargos(TCargos TCargos) {
        this.TCargos = TCargos;
    }
    public TEtapasProduccion getTEtapasProduccion() {
        return this.TEtapasProduccion;
    }
    
    public void setTEtapasProduccion(TEtapasProduccion TEtapasProduccion) {
        this.TEtapasProduccion = TEtapasProduccion;
    }
    public TProductos getTProductos() {
        return this.TProductos;
    }
    
    public void setTProductos(TProductos TProductos) {
        this.TProductos = TProductos;
    }
    public String getDescripcionEspecifica() {
        return this.descripcionEspecifica;
    }
    
    public void setDescripcionEspecifica(String descripcionEspecifica) {
        this.descripcionEspecifica = descripcionEspecifica;
    }
    public BigDecimal getHorasHombre() {
        return this.horasHombre;
    }
    
    public void setHorasHombre(BigDecimal horasHombre) {
        this.horasHombre = horasHombre;
    }
    public byte getNumeroOrden() {
        return this.numeroOrden;
    }
    
    public void setNumeroOrden(byte numeroOrden) {
        this.numeroOrden = numeroOrden;
    }
    public Set getTDetallesEtapas() {
        return this.TDetallesEtapas;
    }
    
    public void setTDetallesEtapas(Set TDetallesEtapas) {
        this.TDetallesEtapas = TDetallesEtapas;
    }
    public Set getTTmaquinaHerramientas() {
        return this.TTmaquinaHerramientas;
    }
    
    public void setTTmaquinaHerramientas(Set TTmaquinaHerramientas) {
        this.TTmaquinaHerramientas = TTmaquinaHerramientas;
    }
    public Set getTDetallesPlans() {
        return this.TDetallesPlans;
    }
    
    public void setTDetallesPlans(Set TDetallesPlans) {
        this.TDetallesPlans = TDetallesPlans;
    }




}


