USE [Ramaty]
GO

/****** Object:  Table [dbo].[T_CAPACIDAD_PRODUCTIVA]    Script Date: 09/11/2011 15:38:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_CAPACIDAD_PRODUCTIVA](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[idMaquinaHerramienta] [numeric](3, 0) NULL,
	[idMaterial] [numeric](3, 0) NULL,
	[capacidad] [int] NULL,
 CONSTRAINT [PK_T_CAPACIDAD_PODUCTIVA] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[T_CAPACIDAD_PRODUCTIVA]  WITH CHECK ADD  CONSTRAINT [FK_T_CAPACIDAD_PODUCTIVA_T_MAQUINAS_HERRAMIENTA_PARTICULAR] FOREIGN KEY([idMaquinaHerramienta])
REFERENCES [dbo].[T_MAQUINAS_HERRAMIENTA_PARTICULAR] ([ID_MAQUINA_HERRAMIENTA_PARTICULAR])
GO

ALTER TABLE [dbo].[T_CAPACIDAD_PRODUCTIVA] CHECK CONSTRAINT [FK_T_CAPACIDAD_PODUCTIVA_T_MAQUINAS_HERRAMIENTA_PARTICULAR]
GO

ALTER TABLE [dbo].[T_CAPACIDAD_PRODUCTIVA]  WITH CHECK ADD  CONSTRAINT [FK_T_CAPACIDAD_PODUCTIVA_T_MATERIALES] FOREIGN KEY([idMaterial])
REFERENCES [dbo].[T_MATERIALES] ([ID_MATERIAL])
GO

ALTER TABLE [dbo].[T_CAPACIDAD_PRODUCTIVA] CHECK CONSTRAINT [FK_T_CAPACIDAD_PODUCTIVA_T_MATERIALES]
GO


