

/*SCRIPT DE ACTUALIZACIÓN*/

/*Cambios solicitados por Rodrigo - 10/08/2011*/

EXEC sp_rename 'T_USUARIOS.CONTRASEÑA', 'CONTRASENIA';
GO
EXEC sp_rename 'T_CLIENTES_WEB.CONTRASEÑA', 'CONTRASENIA';
GO

/*Cambios solicitados por Ivan 13/08/2011*/
ALTER TABLE T_CLIENTES ALTER COLUMN ID_CLIENTE_WEB NUMERIC(5) NULL;
GO
ALTER TABLE T_CLIENTES ALTER COLUMN ID_USUARIO NUMERIC(5) NULL;
GO
ALTER TABLE T_CLIENTES ALTER COLUMN TELEFONO_RESPONSABLE NUMERIC(13) NULL;
GO

/*Cambios solicitados por Gabriela - 15/08/2011*/
ALTER TABLE T_PROVEEDORES ADD FEC_BAJA DATETIME;
GO
ALTER TABLE T_PROVEEDORES ADD MOTIVO_BAJA VARCHAR(100);
GO

CREATE TABLE T_EGRESOS (
       ID_EGRESO            numeric(8) NOT NULL,
       FEC_HORA_EGRESO      datetime NOT NULL,
       CANTIDAD             numeric(5) NOT NULL,
       ID_MATERIAL          numeric(3) NOT NULL
)
GO

ALTER TABLE T_EGRESOS
       ADD PRIMARY KEY (ID_EGRESO ASC)
       
GO

ALTER TABLE T_EGRESOS
       ADD FOREIGN KEY (ID_MATERIAL)
                             REFERENCES T_MATERIALES  (ID_MATERIAL)
                             ON DELETE NO ACTION
                             ON UPDATE NO ACTION
GO
       

