package BaseDeDatos.Ventas;
// Generated 09/08/2011 13:12:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TPedidos generated by hbm2java
 */
public class TPedidos  implements java.io.Serializable {


     private int idPedido;
     private TTpedido TTpedido;
     private TClientes TClientes;
     private TEpedido TEpedido;
     private Boolean entregaMaterial;
     private Date fecHoraEstimadaEntrega;
     private Date fecHoraGeneracion;
     private Date fecHoraRealEntrega;
     private Date fecSolicitada;
     private byte prioridad;
     private Set TPlanesProduccions = new HashSet(0);
     private Set TDetallesPedidos = new HashSet(0);

    public TPedidos() {
    }

	
    public TPedidos(int idPedido, TTpedido TTpedido, TClientes TClientes, TEpedido TEpedido, Date fecHoraEstimadaEntrega, Date fecHoraGeneracion, Date fecHoraRealEntrega, Date fecSolicitada, byte prioridad) {
        this.idPedido = idPedido;
        this.TTpedido = TTpedido;
        this.TClientes = TClientes;
        this.TEpedido = TEpedido;
        this.fecHoraEstimadaEntrega = fecHoraEstimadaEntrega;
        this.fecHoraGeneracion = fecHoraGeneracion;
        this.fecHoraRealEntrega = fecHoraRealEntrega;
        this.fecSolicitada = fecSolicitada;
        this.prioridad = prioridad;
    }
    public TPedidos(int idPedido, TTpedido TTpedido, TClientes TClientes, TEpedido TEpedido, Boolean entregaMaterial, Date fecHoraEstimadaEntrega, Date fecHoraGeneracion, Date fecHoraRealEntrega, Date fecSolicitada, byte prioridad, Set TPlanesProduccions, Set TDetallesPedidos) {
       this.idPedido = idPedido;
       this.TTpedido = TTpedido;
       this.TClientes = TClientes;
       this.TEpedido = TEpedido;
       this.entregaMaterial = entregaMaterial;
       this.fecHoraEstimadaEntrega = fecHoraEstimadaEntrega;
       this.fecHoraGeneracion = fecHoraGeneracion;
       this.fecHoraRealEntrega = fecHoraRealEntrega;
       this.fecSolicitada = fecSolicitada;
       this.prioridad = prioridad;
       this.TPlanesProduccions = TPlanesProduccions;
       this.TDetallesPedidos = TDetallesPedidos;
    }
   
    public int getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }
    public TTpedido getTTpedido() {
        return this.TTpedido;
    }
    
    public void setTTpedido(TTpedido TTpedido) {
        this.TTpedido = TTpedido;
    }
    public TClientes getTClientes() {
        return this.TClientes;
    }
    
    public void setTClientes(TClientes TClientes) {
        this.TClientes = TClientes;
    }
    public TEpedido getTEpedido() {
        return this.TEpedido;
    }
    
    public void setTEpedido(TEpedido TEpedido) {
        this.TEpedido = TEpedido;
    }
    public Boolean getEntregaMaterial() {
        return this.entregaMaterial;
    }
    
    public void setEntregaMaterial(Boolean entregaMaterial) {
        this.entregaMaterial = entregaMaterial;
    }
    public Date getFecHoraEstimadaEntrega() {
        return this.fecHoraEstimadaEntrega;
    }
    
    public void setFecHoraEstimadaEntrega(Date fecHoraEstimadaEntrega) {
        this.fecHoraEstimadaEntrega = fecHoraEstimadaEntrega;
    }
    public Date getFecHoraGeneracion() {
        return this.fecHoraGeneracion;
    }
    
    public void setFecHoraGeneracion(Date fecHoraGeneracion) {
        this.fecHoraGeneracion = fecHoraGeneracion;
    }
    public Date getFecHoraRealEntrega() {
        return this.fecHoraRealEntrega;
    }
    
    public void setFecHoraRealEntrega(Date fecHoraRealEntrega) {
        this.fecHoraRealEntrega = fecHoraRealEntrega;
    }
    public Date getFecSolicitada() {
        return this.fecSolicitada;
    }
    
    public void setFecSolicitada(Date fecSolicitada) {
        this.fecSolicitada = fecSolicitada;
    }
    public byte getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(byte prioridad) {
        this.prioridad = prioridad;
    }
    public Set getTPlanesProduccions() {
        return this.TPlanesProduccions;
    }
    
    public void setTPlanesProduccions(Set TPlanesProduccions) {
        this.TPlanesProduccions = TPlanesProduccions;
    }
    public Set getTDetallesPedidos() {
        return this.TDetallesPedidos;
    }
    
    public void setTDetallesPedidos(Set TDetallesPedidos) {
        this.TDetallesPedidos = TDetallesPedidos;
    }




}


