package Negocio.Ventas;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TEpedido generated by hbm2java
 */
@Entity
@Table(name="T_EPEDIDO"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class EstadoPedido  implements java.io.Serializable {


     private byte idEpedido;
     private String nombre;
     private String descripcion;
     private Set<Pedido> TPedidoses = new HashSet<Pedido>(0);

    public EstadoPedido() {
    }

	
    public EstadoPedido(byte idEpedido, String nombre) {
        this.idEpedido = idEpedido;
        this.nombre = nombre;
    }
    public EstadoPedido(byte idEpedido, String nombre, String descripcion, Set<Pedido> TPedidoses) {
       this.idEpedido = idEpedido;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.TPedidoses = TPedidoses;
    }
   
     @Id 
    
    @Column(name="ID_EPEDIDO", unique=true, nullable=false, precision=2, scale=0)
    public byte getIdEpedido() {
        return this.idEpedido;
    }
    
    public void setIdEpedido(byte idEpedido) {
        this.idEpedido = idEpedido;
    }
    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="DESCRIPCION", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TEpedido")
    public Set<Pedido> getTPedidoses() {
        return this.TPedidoses;
    }
    
    public void setTPedidoses(Set<Pedido> TPedidoses) {
        this.TPedidoses = TPedidoses;
    }




}


