/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaABMEmpleado.java
 *
 * Created on 04/06/2011, 19:47:32
 */

package Presentacion.Administracion;

import Negocio.Administracion.Empleado;
import Negocio.Administracion.GestorEmpleado;
import Negocio.Administracion.Sexo;
import Negocio.Administracion.TipoDocumento;
import Negocio.UbicacionGeografica.Barrio;
import Negocio.UbicacionGeografica.Domicilio;
import Negocio.UbicacionGeografica.Localidad;
import Negocio.UbicacionGeografica.Pais;
import Negocio.UbicacionGeografica.Provincia;
import Presentacion.IniciadorDeVentanas;
import gui.GUILocal;
import java.awt.Dialog;

/**
 *
 * @author Heber Parrucci
 */
public class PantallaABMEmpleado extends javax.swing.JDialog {

    private GestorEmpleado gestor;
    private Empleado empleado=null;
    /** Creates new form PantallaABMEmpleado */
    public PantallaABMEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    public PantallaABMEmpleado(Dialog owner, boolean modal, GestorEmpleado gestor) {
        super(owner, modal);
        GUILocal.establecerGUILocal(this);
        initComponents();
        this.gestor=gestor;

       cargarTipoProductos();
       IniciadorDeVentanas.iniciarVentana(this, this.getWidth(),this.getHeight());
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNumeroDocumento = new javax.swing.JTextField();
        cmbTipoDocumento = new javax.swing.JComboBox();
        cmbSexo = new javax.swing.JComboBox();
        dtcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbBarrio = new javax.swing.JComboBox();
        cmbLocalidad = new javax.swing.JComboBox();
        cmbProvincia = new javax.swing.JComboBox();
        cmbPais = new javax.swing.JComboBox();
        txtDepto = new javax.swing.JTextField();
        txtPiso = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        btnAgregarProvincia = new javax.swing.JButton();
        btnAgregarPais = new javax.swing.JButton();
        btnAgregarLocalidad = new javax.swing.JButton();
        btnAgregarBarrio = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lista = new Presentacion.JCheckList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));

        jLabel1.setText("Nombre:");

        Apellido.setText("Apellido:");

        jLabel3.setText("Tipo Documento:");

        jLabel2.setText("Número Documento:");

        jLabel4.setText("Fecha de Nacimiento:");

        jLabel5.setText("Sexo:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtNumeroDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDocumentoActionPerformed(evt);
            }
        });

        cmbTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dtcFechaNacimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtcFechaNacimientoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(Apellido)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbTipoDocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNumeroDocumento)
                    .addComponent(txtNombre)
                    .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtcFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(dtcFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Domicilio"));
        jPanel2.setLayout(null);

        jLabel6.setText("País:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 43, 23, 14);

        jLabel7.setText("Provincia:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(16, 77, 47, 14);

        jLabel8.setText("Localidad:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(16, 111, 48, 14);

        jLabel9.setText("Barrio:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(32, 144, 32, 14);

        jLabel10.setText("Calle:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(40, 192, 27, 14);

        jLabel11.setText("Número:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(240, 190, 41, 14);

        jLabel14.setText("Depto:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(32, 230, 33, 14);

        jLabel12.setText("Piso:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(250, 230, 23, 14);

        cmbBarrio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cmbBarrio);
        cmbBarrio.setBounds(74, 141, 120, 20);

        cmbLocalidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cmbLocalidad);
        cmbLocalidad.setBounds(74, 108, 120, 20);

        cmbProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cmbProvincia);
        cmbProvincia.setBounds(73, 74, 120, 20);

        cmbPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cmbPais);
        cmbPais.setBounds(73, 40, 120, 20);

        txtDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeptoActionPerformed(evt);
            }
        });
        jPanel2.add(txtDepto);
        txtDepto.setBounds(75, 227, 140, 20);
        jPanel2.add(txtPiso);
        txtPiso.setBounds(290, 230, 86, 20);
        jPanel2.add(txtNumero);
        txtNumero.setBounds(290, 190, 86, 20);
        jPanel2.add(txtCalle);
        txtCalle.setBounds(77, 189, 140, 20);

        btnAgregarProvincia.setText("Agregar");
        jPanel2.add(btnAgregarProvincia);
        btnAgregarProvincia.setBounds(210, 70, 71, 23);

        btnAgregarPais.setText("Agregar");
        jPanel2.add(btnAgregarPais);
        btnAgregarPais.setBounds(210, 40, 71, 23);

        btnAgregarLocalidad.setText("Agregar");
        jPanel2.add(btnAgregarLocalidad);
        btnAgregarLocalidad.setBounds(210, 110, 71, 23);

        btnAgregarBarrio.setText("Agregar");
        jPanel2.add(btnAgregarBarrio);
        btnAgregarBarrio.setBounds(210, 140, 71, 23);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Contacto"));

        jLabel13.setText("Teléfono:");

        jLabel15.setText("Celular:");

        jLabel16.setText("E-Mail:");

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addGap(161, 161, 161))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargos"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNumeroDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDocumentoActionPerformed

    private void txtDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeptoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:

          if(validar()){
           empleado.setNombre(txtNombre.getText().toUpperCase());
           empleado.setApellido(txtApellido.getText().toUpperCase());
           empleado.setTTdocumento((TipoDocumento) cmbTipoDocumento.getSelectedItem());
           empleado.setNumeroDocumento(Integer.parseInt(txtNumeroDocumento.getText()));
           empleado.setFecNacimiento(dtcFechaNacimiento.getDate());
           empleado.setTSexos((Sexo) cmbSexo.getSelectedItem());
           empleado.setTelefono(Long.parseLong(txtTelefono.getText()));
           empleado.setCelular(Long.parseLong(txtCelular.getText()));
           empleado.setCorreoElectronico(txtEmail.getText());


           Domicilio domicilio=empleado.getTDomicilios();
           domicilio.setTPaises((Pais) cmbPais.getSelectedItem());
           domicilio.setTProvincias((Provincia) cmbProvincia.getSelectedItem());
           domicilio.setTLocalidades((Localidad) cmbLocalidad.getSelectedItem());
           domicilio.setTBarrios((Barrio) cmbBarrio.getSelectedItem());
           domicilio.setCalle(txtCalle.getText());
           domicilio.setNumero(Integer.parseInt(txtNumero.getText()));
           domicilio.setDepto(txtDepto.getText());
           domicilio.setPiso(Short.parseShort(txtPiso.getText()));




           

//            if(txtFechaBaja.getText().compareTo("")!=0){
//                producto.setFecBaja(new Date());
//                producto.setMotivoBaja(txtMotivoBaja.getText());
//            }
//
//
//            try {
//                gestor.ejecutarOperacion(empleado);
//                Mensajes.mensajeInformacion(gestor.mensajeResultado(empleado.getApellido()+", "+empleado.getNombre()));
//                this.vaciar();
//                gestor.reiniciar(this);
//
//            } catch (ExceptionGestor ex) {
//                Logger.getLogger(PantallaABMProducto.class.getName()).log(Level.SEVERE, null, ex);
//            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void dtcFechaNacimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtcFechaNacimientoMouseClicked
        // TODO add your handling code here:

      //  txtFechaEstimada.setText(Utilidades.parseFecha(dtcFechaNacimiento.getDate()));
}//GEN-LAST:event_dtcFechaNacimientoMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PantallaABMEmpleado dialog = new PantallaABMEmpleado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregarBarrio;
    private javax.swing.JButton btnAgregarLocalidad;
    private javax.swing.JButton btnAgregarPais;
    private javax.swing.JButton btnAgregarProvincia;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cmbBarrio;
    private javax.swing.JComboBox cmbLocalidad;
    private javax.swing.JComboBox cmbPais;
    private javax.swing.JComboBox cmbProvincia;
    private javax.swing.JComboBox cmbSexo;
    private javax.swing.JComboBox cmbTipoDocumento;
    private com.toedter.calendar.JDateChooser dtcFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private Presentacion.JCheckList lista;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDepto;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumeroDocumento;
    private javax.swing.JTextField txtPiso;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables


    private boolean validar(){
        return true;
    }

     private void cargarDatos(Empleado empleado){

         this.txtNombre.setText(empleado.getNombre());
         this.txtApellido.setText(empleado.getApellido());
         TipoDocumento tipo=null;
        for(int i=0; i<cmbTipoDocumento.getItemCount();i++){
            tipo=(TipoDocumento) cmbTipoDocumento.getItemAt(i);
            if(tipo.getNombre().compareTo(this.empleado.getTTdocumento().getNombre())==0){
                cmbTipoDocumento.setSelectedIndex(i);
                break;
            }
         }

         this.txtNumeroDocumento.setText(empleado.getNumeroDocumento()+"");
         this.txtTelefono.setText(empleado.getTelefono()+"");
         this.txtCelular.setText(empleado.getCelular()+"");
         this.txtEmail.setText(empleado.getCorreoElectronico());

         Pais pais=null;
        for(int i=0; i<cmbPais.getItemCount();i++){
            pais=(Pais) cmbPais.getItemAt(i);
            if(pais.getNombre().compareTo(this.empleado.getTDomicilios().getTPaises().getNombre())==0){
                cmbPais.setSelectedIndex(i);
                break;
            }
         }

         this.cargarProvicias(pais);


          Provincia provincia=null;
        for(int i=0; i<cmbProvincia.getItemCount();i++){
            provincia=(Provincia) cmbProvincia.getItemAt(i);
            if(provincia.getNombre().compareTo(this.empleado.getTDomicilios().getTProvincias().getNombre())==0){
                cmbProvincia.setSelectedIndex(i);
                break;
            }
         }

          this.cargarLocalidades(provincia);

            Localidad localidad=null;
        for(int i=0; i<cmbLocalidad.getItemCount();i++){
            localidad=(Localidad) cmbLocalidad.getItemAt(i);
            if(localidad.getNombre().compareTo(this.empleado.getTDomicilios().getTLocalidades().getNombre())==0){
                cmbLocalidad.setSelectedIndex(i);
                break;
            }
         }

            this.cargarBarrio(localidad);

             Barrio barrio=null;
        for(int i=0; i<cmbBarrio.getItemCount();i++){
            barrio=(Barrio) cmbBarrio.getItemAt(i);
            if(barrio.getNombre().compareTo(this.empleado.getTDomicilios().getTBarrios().getNombre())==0){
                cmbBarrio.setSelectedIndex(i);
                break;
            }
         }

          this.txtCalle.setText(empleado.getTDomicilios().getCalle());
          this.txtPiso.setText(empleado.getTDomicilios().getPiso()+"");
          this.txtNumero.setText(empleado.getTDomicilios().getNumero()+"");
          this.txtDepto.setText(empleado.getTDomicilios().getDepto());

    }

     private void cargarTipoProductos(){
      
    }

    public void nuevo(){
       
    }

    public void modificar(Empleado emp){
       
    }

    public void baja(Empleado emp) {
       
        }

    public void vaciar(){
      
    }

    private void activarProducto(boolean flag){
        
    }

    private void activarBaja(boolean flag){
        
    }

    private void activarBotones(boolean aceptar,boolean cancelar, boolean alta){
      
    }

    private void cargarPais(){

    }
    private void cargarProvicias(Pais pais){

    }
    private void cargarLocalidades(Provincia provincia){

    }

    private void cargarBarrio(Localidad localidad){
        
    }



    private void activarDomicilio(boolean pais,boolean provincia, boolean localidad, boolean barrio){
        this.cmbPais.setEnabled(pais);
        this.cmbProvincia.setEnabled(provincia);
        this.cmbLocalidad.setEnabled(localidad);
        this.cmbBarrio.setEnabled(barrio);
        
    }

}
