package Negocio.Produccion;
// Generated 31-oct-2011 2:17:29 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TMaqHerrPartXDetPlan generated by hbm2java
 */
@Entity
@Table(name = "T_HERR_PART_X_DET_PLAN", schema = "dbo", catalog = "Ramaty")
public class DetallePlanXHerramientaParticular implements java.io.Serializable {

    @Id
    @GeneratedValue
    @Column(name = "ID_HERR_PART_X_DET_PLAN", unique = true, nullable = false, precision = 10, scale = 0)
    private long idMaqHerrPartXDetPlan;
    //____________________________________________________________________________________________________//
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_DETALLE_PLAN", nullable = false)
    private DetallePlanProduccion TDetallesPlan;
    //____________________________________________________________________________________________________//
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_HERRAMIENTA_PARTICULAR")
    private HerramientaParticular THerramientasParticular;

    public DetallePlanXHerramientaParticular() {
    }

    public DetallePlanXHerramientaParticular(HerramientaParticular THerramientasParticular) {
        this.THerramientasParticular = THerramientasParticular;
    }

    public long getIdMaqHerrPartXDetPlan() {
        return this.idMaqHerrPartXDetPlan;
    }

    public void setIdMaqHerrPartXDetPlan(long idMaqHerrPartXDetPlan) {
        this.idMaqHerrPartXDetPlan = idMaqHerrPartXDetPlan;
    }

    public DetallePlanProduccion getTDetallesPlan() {
        return this.TDetallesPlan;
    }

    public void setTDetallesPlan(DetallePlanProduccion TDetallesPlan) {
        this.TDetallesPlan = TDetallesPlan;
    }

    public HerramientaParticular getTHerramientasParticular() {
        return this.THerramientasParticular;
    }

    public void setTHerramientasParticular(HerramientaParticular THerramientasParticular) {
        this.THerramientasParticular = THerramientasParticular;
    }
}
