package Negocio.Produccion;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TEmaquina generated by hbm2java
 */
@Entity
@Table(name="T_EMAQUINA"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class EstadoMaquina  implements java.io.Serializable {


     private byte idEmaquina;
     private Serializable nombre;
     private String descripcion;
     private Set<MaquinaHerramientaParticular> TMaquinasHerramientaParticulars = new HashSet<MaquinaHerramientaParticular>(0);

    public EstadoMaquina() {
    }

	
    public EstadoMaquina(byte idEmaquina, Serializable nombre) {
        this.idEmaquina = idEmaquina;
        this.nombre = nombre;
    }
    public EstadoMaquina(byte idEmaquina, Serializable nombre, String descripcion, Set<MaquinaHerramientaParticular> TMaquinasHerramientaParticulars) {
       this.idEmaquina = idEmaquina;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.TMaquinasHerramientaParticulars = TMaquinasHerramientaParticulars;
    }
   
     @Id 
    
    @Column(name="ID_EMAQUINA", unique=true, nullable=false, precision=2, scale=0)
    public byte getIdEmaquina() {
        return this.idEmaquina;
    }
    
    public void setIdEmaquina(byte idEmaquina) {
        this.idEmaquina = idEmaquina;
    }
    
    @Column(name="NOMBRE", nullable=false)
    public Serializable getNombre() {
        return this.nombre;
    }
    
    public void setNombre(Serializable nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="DESCRIPCION", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TEmaquina")
    public Set<MaquinaHerramientaParticular> getTMaquinasHerramientaParticulars() {
        return this.TMaquinasHerramientaParticulars;
    }
    
    public void setTMaquinasHerramientaParticulars(Set<MaquinaHerramientaParticular> TMaquinasHerramientaParticulars) {
        this.TMaquinasHerramientaParticulars = TMaquinasHerramientaParticulars;
    }




}


