package Negocio.Produccion;
// Generated 23/10/2011 15:28:32 by Hibernate Tools 3.2.1.GA


import Negocio.Administracion.Empleado;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOrdenesTrabajo generated by hbm2java
 */
@Entity
@Table(name="T_ORDENES_TRABAJO"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class OrdenTrabajo  implements java.io.Serializable {


     private long idOrdenTrabajo;
     private Empleado TEmpleados;
     private EstadoOrdenTrabajo TEordenTrabajo;
     private Date fecEmision;
     private String observaciones;
     private Set<DetallePlanProduccion> TDetallesPlans = new HashSet(0);
     

    public OrdenTrabajo() {
    }

	
    public OrdenTrabajo(long idOrdenTrabajo, Empleado TEmpleados, EstadoOrdenTrabajo TEordenTrabajo, Date fecEmision) {
        this.idOrdenTrabajo = idOrdenTrabajo;
        this.TEmpleados = TEmpleados;
        this.TEordenTrabajo = TEordenTrabajo;
        this.fecEmision = fecEmision;
        
    }
    public OrdenTrabajo(long idOrdenTrabajo, Empleado TEmpleados, EstadoOrdenTrabajo TEordenTrabajo, Date fecEmision, String observaciones, Set TDetallesPlans) {
       this.idOrdenTrabajo = idOrdenTrabajo;
       this.TEmpleados = TEmpleados;
       this.TEordenTrabajo = TEordenTrabajo;
       this.fecEmision = fecEmision;
       this.observaciones = observaciones;
        this.TDetallesPlans = TDetallesPlans;
       
    }
   
     @Id 
    @GeneratedValue
    @Column(name="ID_ORDEN_TRABAJO", unique=true, nullable=false, precision=10, scale=0)
    public long getIdOrdenTrabajo() {
        return this.idOrdenTrabajo;
    }
    
    public void setIdOrdenTrabajo(long idOrdenTrabajo) {
        this.idOrdenTrabajo = idOrdenTrabajo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_EMPLEADO", nullable=false)
    public Empleado getTEmpleados() {
        return this.TEmpleados;
    }
    
    public void setTEmpleados(Empleado TEmpleados) {
        this.TEmpleados = TEmpleados;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_EORDEN_TRABAJO", nullable=false)
    public EstadoOrdenTrabajo getTEordenTrabajo() {
        return this.TEordenTrabajo;
    }
    
    public void setTEordenTrabajo(EstadoOrdenTrabajo TEordenTrabajo) {
        this.TEordenTrabajo = TEordenTrabajo;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_EMISION", nullable=false, length=23)
    public Date getFecEmision() {
        return this.fecEmision;
    }
    
    public void setFecEmision(Date fecEmision) {
        this.fecEmision = fecEmision;
    }
    
    @Column(name="OBSERVACIONES", length=20)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TOrdenesTrabajo")
    public List<DetallePlanProduccion> getTDetallesPlans() {
        return new ArrayList<DetallePlanProduccion>(TDetallesPlans); 
    }

    public void setTDetallesPlans(Set<DetallePlanProduccion> TDetallesPlans) {
        this.TDetallesPlans = TDetallesPlans;
    }

    public PlanProduccion obtenerPlanProduccion(){
        DetallePlanProduccion detalle=this.getTDetallesPlans().iterator().next();
        return detalle.getTPlanesProduccion();
    }
  



}


