              /* SCRIPT DE INICIALIZACIÓN RAMATY*/
              

/* DELETE permite borrar las filas que contiene una tabla. */

DELETE FROM T_PROVINCIAS
DELETE FROM T_PAISES
DELETE FROM T_LOCALIDADES
DELETE FROM T_TPRODUCTO


/* DBCC permite resetear los id  (La PK de la tabla) , luego de cada DELETE. Ejemplos: 1) Si se borraron todas la filas
de una tabla, insertando nuevas filas los id (La PK de la tabla) comienzan en uno. */

DBCC CHECKIDENT ('T_PROVINCIAS', RESEED,0) 
DBCC CHECKIDENT ('T_PAISES', RESEED,0) 
DBCC CHECKIDENT ('T_LOCALIDADES', RESEED,0)
DBCC CHECKIDENT ('T_TPRODUCTO', RESEED,0)


/*Inserción de datos en la tabla tPaises*/

INSERT INTO T_PAISES
            (NOMBRE,
           DESCRIPCION)
     VALUES 
           ('AFGANISTAN',' '),
           ('ISLAS GLAND',' '),
           ('ALBANIA',' '),
           ('ALEMANIA',' '),
           ('ANDORRA',' '),
           ('ANGOLA',' '),
           ('ANGUILLA',' '),
           ( 'ANTÁRTIDA',' '),
           ('ANTIGUA Y BARBUDA',' '),
           ('ANTILLAS HOLANDESAS',' '),
           ('ARABIA SAUDÍ',' '),
           ('ARGELIA',' '),
           ('ARGENTINA',' '),
           ( 'ARMENIA',' '),
           ('ARUBA',' '),
           ('AUSTRALIA',' '),
           ('AUSTRIA',' '),
           ('AZERBAIYÁN',' '),
           ('BAHAMAS',' '),
           ( 'BAHRÉIN',' '),
           ('BANGLADESH',' '),
           ('BARBADOS',' '),
           ('BIELORRUSIA',' '),
           ('BÉLGICA',' '),
           ( 'BELICE',' '),
           ('BENIN',' '),
           ('BERMUDAS',' '),
           ('BHUTÁN',' '),
           ('BOLIVIA',' '),
           ('BOSNIA Y HERZEGOVINA',' '),
           ( 'BOTSUANA',' '),
           ('ISLA BOUVET',' '),
           ('BRASIL',' '),
           ('BRUNÉI',' '),
           ('BULGARIA',' '),
           ('BURKINA FASO',' '),
           ( 'BURUNDI',' '),
           ('CABO VERDE',' '),
           ('ISLAS CAIMÁN',' '),
           ('CAMBOYA',' '),
           ('CAMERÚN',' '),
           ('CANADÁ',' '),
           ( 'REPÚBLICA CENTROAFRICANA',' '),
           ('CHAD',' '),
           ('REPÚBLICA CHECA',' '),
           ('CHILE',' '),
           ('CHINA',' '),
           ('CHIPRE',' '),
           ( 'ISLA DE NAVIDAD',' '),
           ('CIUDAD DEL VATICANO',' '),
           ('ISLAS COCOS',' '),
           ('COLOMBIA',' '),
           ('COMORAS',' '),
           ('REPÚBLICA DEMOCRÁTICA DEL CONGO',' '),
           ( 'CONGO',' '),
           ('ISLAS COOK',' '),
           ('COREA DEL NORTE',' '),
           ('COREA DEL SUR',' '),
           ('COSTA DEL MARFIL',' '),
           ('COSTA RICA',' '),
           ( 'CROACIA',' '),
           ('CUBA',' '),
           ('DINAMARCA',' '),
           ('DOMINICA',' '),
           ('REPÚBLICA DOMINICANA',' '),
           ('ECUADOR',' '),
           ( 'EGIPTO',' '),
           ('EL SALVADOR',' '),
           ('EMIRATOS ÁRABES UNIDOS',' '),
           ('ERITREA',' '),
           ('ESLOVAQUIA',' '),
           ('ESPAÑA',' '),
           ( 'ISLAS ULTRAMARINAS DE ESTADOS UNIDOS',' '),
           ('ESTADOS UNIDOS',' '),
           ('ESTONIA',' '),
           ('ETIOPÍA',' '),
           ('ISLAS FEROE',' '),
           ('FILIPINAS',' '),
           ( 'FINLANDIA',' '),
           ('FIYI',' '),
           ('FRANCIA',' '),
           ('GABÓN',' '),
           ('GAMBIA',' '),
           ('GEORGIA',' '),
           ( 'ISLAS GEORGIAS DEL SUR Y SANDUWICH DEL SUR',' '),
           ('GHANA',' '),
           ('GIBRALTAR',' '),
           ('GRANADA',' '),
           ('GRECIA',' '),
           ('GROENLANDIA',' '),
           ( 'GUADALUPE',' '),
           ('GUAM',' '),
           ('GUATEMALA',' '),
           ('GUAYANA FRANCESA',' '),
           ('GUINEA',' '),
           ('GUINEA ECUATORIAL',' '),
           ( 'GUINEA-BISSAU',' '),
           ('GUYANA',' '),
           ('HAITÍ',' '),
           ('ISLAS HEARD Y MCDONALD',' '),
           ('HONDURAS',' '),
           ('HONG KONG',' '),
           ( 'HUNGRÍA',' '),
           ('INDIA',' '),
           ('INDONESIA',' '),
           ('IRÁN',' '),
           ('IRAQ',' '),
           ('IRLANDA',' '),
           ( 'ISLANDIA',' '),
           ('ISRAEL',' '),
           ('ITALIA',' '),
           ('JAMAICA',' '),
           ('JAPÓN',' '),
           ('JORDANIA',' '),
           ( 'KAZAJSTÁN',' '),
           ('KENIA',' '),
           ('KIRGUISTÁN',' '),
           ('KIRIBATI',' '),
           ('KUWAIT',' '),
           ('LAOS',' '),
           ( 'LESOTHO',' '),
           ('LETONIA',' '),
           ('LÍBANO',' '),
           ('LIBERIA',' '),
           ('LIBIA',' '),
           ('LIECHTENSTEIN',' '),
           ( 'LITUANIA',' '),
           ('LUXEMBURGO',' '),
           ('MACAO',' '),
           ('ARY MACEDONIA',' '),
           ('MADAGASCAR',' '),
           ('ANGUILLA',' '),
           ( 'MALASIA',' '),
           ('MALAWI',' '),
           ('MALDIVAS',' '),
           ('MALÍ',' '),
           ('ISLAS MALVINAS',' '),
           ('ISLAS MARIANAS DEL NORTE',' '),
           ( 'MARRUECOS',' '),
           ('ISLAS MARSHALL',' '),
           ('MARTINICA',' '),
           ('MAURICIO',' '),
           ('MAURITANIA',' '),
           ('MAYOTTE',' '),
           ( 'MÉXICO',' '),
           ('MICRONESIA',' '),
           ('MOLDAVIA',' '),
           ('MÓNACO',' '),
           ('MONGOLIA',' '),
           ('MONTSERRAT',' '),
           ( 'MOZAMBIQUE',' '),
           ('MYANMAR',' '),
           ('NAMIBIA',' '),
           ('NAURU',' '),
           ('NEPAL',' '),
           ('NICARAGUA',' '),
           ( 'NÍGER',' '),
           ('NIGERIA',' '),
           ('NIUE',' '),
           ('ISLA NORFOLK',' '),
           ('NORUEGA',' '),
           ('NUEVA CALEDONIA',' '),
           ( 'NUEVA ZELANDA',' '),
           ('OMÁN',' '),
           ('PAÍSES BAJOS',' '),
           ('PAKISTÁN',' '),
           ('PALAU',' '),
           ('PALESTINA',' '),
           ( 'PANAMÁ',' '),
           ('PAPÚA NUEVA GUINEA',' '),
           ('PARAGUAY',' '),
           ('PERÚ',' '),
           ('ISLAS PITCAIRN',' '),
           ('POLINESIA FRANCESA',' '),
           ( 'POLONIA',' '),
           ('PORTUGAL',' '),
           ('PUERTO RICO',' '),
           ('QATAR',' '),
           ('REINO UNIDO',' '),
           ('REUNIÓN',' '),
           ( 'RUANDA',' '),
           ('RUMANIA',' '),
           ('RUSIA',' '),
           ('SAHARA OCCIDENTAL',' '),
           ('ISLAS SALOMÓN',' '),
           ('SAMOA',' '),
           ( 'SAMOA AMERICANA',' '),
           ('SAN CRISTÓBAL Y NEVIS',' '),
           ('SAN MARINO',' '),
           ('SAN PEDRO Y MIQUELÓN', ' '),
           ('SAN VICENTE Y LAS GRANADINAS', ' '),
           ('SANTA HELENA', ' '),
           ( 'SANTA LUCÍA', ' '),
           ('SANTO TOMÉ Y PRÍNCIPE', ' '),
           ('SENEGAL', ' '),
           ('SERBIA Y MONTENEGRO', ' '),
           ('SEYCHELLES', ' '),
            ('SIERRA LEONA', ' '),
           ( 'SINGAPUR', ' '),
           ('SIRIA', ' '),
           ('SOMALIA', ' '),
           ('SRI LANKA', ' '),
           ('SUAZILANDIA', ' '),
           ('SUDÁFRICA', ' '),
           ( 'SUDÁN', ' '),
           ('SUECIA', ' '),
           ('SUIZA', ' '),
           ('SURINAM', ' '),
           ('SVALBARD Y JAN MAYEN', ' '),
           ('TAILANDIA', ' '),
           ( 'TAIWÁN', ' '),
           ('TANZANIA', ' '),
           ('TAYIKISTÁN', ' '),
           ('TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO', ' '),
           ('TERRITORIOS AUSTRALES FRANCESES', ' '),
            ('TIMOR ORIENTAL', ' '),
           ( 'TOGO', ' '),
           ('TOKELAU', ' '),
           ('TONGA', ' '),
           ('TRINIDAD Y TOBAGO', ' '),
           ('TÚNEZ', ' '),
           ('ANGUILLA', ' '),
           ( 'ISLAS TURCAS Y CAICOS', ' '),
           ('TURKMENISTÁN', ' '),
           ('TURQUÍA', ' '),
           ('TUVALU', ' '),
           ('UCRANIA', ' '),
           ('UGANDA', ' '),
           ( 'URUGUAY', ' '),
           ('UZBEKISTÁN', ' '),
           ('VANUATU', ' '),
           ('VENEZUELA', ' '),
           ('VIETNAM', ' '),
           ('ISLAS VÍRGENES BRITÁNICAS', ' '),
           ('ISLAS VÍRGENES DE LOS ESTADOS UNIDOS', ' '),
           ( 'WALLIS Y FUTUNA', ' '),
           ('YEMEN', ' '),
           ('YIBUTI', ' '),
           ('ZAMBIA', ' '),
           ('ZIMBABUE', ' '),
           ('GUERNSEY', ' '),
			('JERSEY', ' '),
			('ISLA DE MAN', ' '),
			('MONTENEGRO', ' '),
			('SAN BARTOLOME', ' '),
			('SAINT-MARTIN', ' '),
			('SERBIA', ' ')
			

GO


              
/*Inserción de datos en la tabla tProvincias*/
INSERT INTO T_PROVINCIAS
           (NOMBRE,
            ID_PAIS,
            DESCRIPCION
            )
     VALUES          
( 'SALTA',13,' '),
( 'BUENOS AIRES',13,' '),
( 'CIUDAD AUTÓNOMA DE BS. AS.',13,' '),
( 'SAN LUIS',13,' '),
( 'ENTRE RÍOS',13,' '),
( 'LA RIOJA',13,' '),
( 'SANTIAGO DEL ESTERO',13,' '),
( 'CHACO',13,' '),
( 'SAN JUAN',13,' '),
( 'CATAMARCA',13,' '),
( 'LA PAMPA',13,' '),
( 'MENDOZA',13,' '),
( 'MISIONES',13,' '),
( 'FORMOSA',13,' '),
( 'NEUQUÉN',13,' '),
( 'RÍO NEGRO',13,' '),
( 'SANTA FE',13, 1),
( 'TUCUMÁN',13,' '),
( 'CHUBUT',13,' '),
( 'TIERRA DEL FUEGO',13,' '),
( 'CORRIENTES',13,' '),
( 'CÓRDOBA',13,' '),
( 'JUJUY',13,' '),
( 'SANTA CRUZ',13,' ')
GO
         
/*Inserción de datos en la tabla tLocalidades*/

INSERT INTO T_LOCALIDADES
            (NOMBRE,
           DESCRIPCION,
           ID_PROVINCIA)
     VALUES          
  ('ARROYITO',' ',21),
  ('BELLA VISTA',' ',21),
  ('COLONIA CAROYA',' ',21),
  ('JESUS MARIA',' ',21),
  ('VILLA LUJAN',' ',21),
  ('KILOMETRO TRECE',' ',21),
  ('VILLA MARIA',' ',21),
  ('TOTORAL',' ',21),
  ('LOMA ALTA',' ',21),
  ('LA AURORA',' ',21),
  ('EL CARMEN',' ',21),
  ('COLONIA SANTA ROSA',' ',21),
  ('SAN FRANCISCO',' ',21),
  ('SAN FERNANDO',' ',21)

GO
/*Inserción de datos en la tabla T_TPRODUCTO*/
  
  
  
insert into T_TPRODUCTO (DESCRIPCION,NOMBRE, CODIGO) 
      values 
       ('PRODUCTO DESTINADO A LA CONECCIÓN DE VARIOS CAÑOS','RAMAL', 'RAM'),
       ('PRODUCTO DESTINADO A LA CONECCIÓN DE CAÑOS DE DISTINTOS DIAMETROS','REDUCCIÓN','RED')

             