

                                   /*SCRIPT DE ACTUALIZACIÓN*/


                  /* CAMBIOS SOLICITADOS A PARTIR DEL SCRIPT DE CREACIÓN 1-0 */


/*Cambios solicitados por Rodrigo - 10/08/2011*/

EXEC sp_rename 'T_USUARIOS.CONTRASEÑA', 'CONTRASENIA';
GO
EXEC sp_rename 'T_CLIENTES_WEB.CONTRASEÑA', 'CONTRASENIA';
GO

/*Cambios solicitados por Ivan 13/08/2011*/
ALTER TABLE T_CLIENTES ALTER COLUMN ID_CLIENTE_WEB NUMERIC(5) NULL;
GO
ALTER TABLE T_CLIENTES ALTER COLUMN ID_USUARIO NUMERIC(5) NULL;
GO
ALTER TABLE T_CLIENTES ALTER COLUMN TELEFONO_RESPONSABLE NUMERIC(13) NULL;
GO
ALTER TABLE T_CARGOS DROP CONSTRAINT FK__T_CARGOS__ID_EMP__2B0A656D;
ALTER TABLE T_CARGOS DROP COLUMN ID_EMPLEADO;
GO

CREATE TABLE T_EMPLEADOS_X_CARGO (
       ID_EMPLEADO_X_CARGO  numeric(5) IDENTITY,
       ID_CARGO             numeric(2) NOT NULL,
       ID_EMPLEADO          numeric(5) NOT NULL)
GO

ALTER TABLE T_EMPLEADOS_X_CARGO
       ADD PRIMARY KEY (ID_EMPLEADO_X_CARGO ASC)

GO

ALTER TABLE T_EMPLEADOS_X_CARGO
       ADD FOREIGN KEY (ID_EMPLEADO)
                             REFERENCES T_EMPLEADOS  (ID_EMPLEADO)
                             ON DELETE NO ACTION
                             ON UPDATE NO ACTION
GO

ALTER TABLE T_EMPLEADOS_X_CARGO
       ADD FOREIGN KEY (ID_CARGO)
                             REFERENCES T_CARGOS  (ID_CARGO)
                             ON DELETE NO ACTION
                             ON UPDATE NO ACTION
GO              
ALTER TABLE T_PRODUCTOS DROP COLUMN CODIGO;
GO
ALTER TABLE T_TPRODUCTO ADD CODIGO VARCHAR(4) NOT NULL;
GO
ALTER TABLE T_EMPLEADOS DROP COLUMN LEGAJO;
GO

/*Cambios solicitados por Gabriela - 15/08/2011*/
ALTER TABLE T_PROVEEDORES ADD FEC_BAJA DATETIME;
GO
ALTER TABLE T_PROVEEDORES ADD MOTIVO_BAJA VARCHAR(100);
GO

CREATE TABLE T_EGRESOS (
       ID_EGRESO            numeric(8) NOT NULL,
       FEC_HORA_EGRESO      datetime NOT NULL,
       CANTIDAD             numeric(5) NOT NULL,
       ID_MATERIAL          numeric(3) NOT NULL
)
GO

ALTER TABLE T_EGRESOS
       ADD PRIMARY KEY (ID_EGRESO ASC)
       
GO

ALTER TABLE T_EGRESOS
       ADD FOREIGN KEY (ID_MATERIAL)
                             REFERENCES T_MATERIALES  (ID_MATERIAL)
                             ON DELETE NO ACTION
                             ON UPDATE NO ACTION
GO
       

/*Cambios solicitados por Gabriela 18/08/2011*/

ALTER TABLE T_TPRODUCTO ADD FEC_BAJA DATETIME
GO
ALTER TABLE T_TPRODUCTO ADD MOTIVO_BAJA VARCHAR(100)
GO
ALTER TABLE T_PRODUCTOS ADD FEC_BAJA DATETIME
GO
ALTER TABLE T_PRODUCTOS ADD MOTIVO_BAJA VARCHAR(100)
GO

/*Cambios solicitados por Ivan 18/08/2011*/

ALTER TABLE T_TMAQUINA_HERRAMIENTA ADD FEC_BAJA DATETIME
GO
ALTER TABLE T_TMAQUINA_HERRAMIENTA ADD MOTIVO_BAJA VARCHAR(100)
GO

ALTER TABLE T_MAQUINAS_HERRAMIENTA_PARTICULAR ADD FEC_BAJA DATETIME
GO
ALTER TABLE T_MAQUINAS_HERRAMIENTA_PARTICULAR ADD MOTIVO_BAJA VARCHAR(100)
GO

ALTER TABLE T_PEDIDOS ADD FEC_BAJA DATETIME
GO
ALTER TABLE T_PEDIDOS ADD MOTIVO_BAJA VARCHAR(100)
GO

ALTER TABLE T_CLIENTES ADD FEC_BAJA DATETIME
GO
ALTER TABLE T_CLIENTES ADD MOTIVO_BAJA VARCHAR(100)
GO
ALTER TABLE T_PRODUCTOS ADD CONSTRAINT R_UNIQ_PROD_NOM UNIQUE (NOMBRE)
GO
ALTER TABLE T_CLIENTES ADD CONSTRAINT R_UNIQ_CLI_CUIL UNIQUE (CUIL)
GO
ALTER TABLE T_TPRODUCTO ADD CONSTRAINT R_UNIQ_TPROD_NOM UNIQUE (NOMBRE)
GO
ALTER TABLE T_TDOCUMENTO ADD CONSTRAINT R_UNIQ_TDOC_NOM UNIQUE (NOMBRE)
GO
ALTER TABLE T_CARGOS ADD CONSTRAINT R_UNIQ_CARG_NOM UNIQUE (NOMBRE)
GO
ALTER TABLE T_TPRODUCTO ADD CONSTRAINT R_UNIQ_TPROD_COD UNIQUE (CODIGO)
GO
