package Negocio.Administracion;
// Generated 21/10/2011 13:42:06 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TAsignacionesHorario generated by hbm2java
 */
@Entity
@Table(name = "T_ASIGNACIONES_HORARIO", schema = "dbo", catalog = "Ramaty")
public class AsignacionesHorario implements java.io.Serializable, Comparable<AsignacionesHorario> {

    @Id
    @GeneratedValue
    @Column(name = "ID_ASIGNACION_HORARIO", unique = true, nullable = false, precision = 4, scale = 0)
    private short idAsignacionHorario;
    /*---------------------------------------------------------------------------------------------*/
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_HORARIO", nullable = false)
    private Horarios THorarios;
    /*---------------------------------------------------------------------------------------------*/
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FEC_HASTA", length = 23)
    private Date fecHasta;
    /*---------------------------------------------------------------------------------------------*/
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "FEC_DESDE", nullable = false, length = 23)
    private Date fecDesde;
    /*---------------------------------------------------------------------------------------------*/
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_EMPLEADO")
    private Empleado empleado;

    public AsignacionesHorario() {
    }

    public AsignacionesHorario(short idAsignacionHorario, Horarios THorarios, Date fecDesde) {
        this.idAsignacionHorario = idAsignacionHorario;
        this.THorarios = THorarios;
        this.fecDesde = fecDesde;
    }

    public Empleado getEmpleado() {
        return empleado;
    }

    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    public short getIdAsignacionHorario() {
        return this.idAsignacionHorario;
    }

    public void setIdAsignacionHorario(short idAsignacionHorario) {
        this.idAsignacionHorario = idAsignacionHorario;
    }

    public Horarios getHorario() {
        return this.THorarios;
    }

    public void setTHorarios(Horarios THorarios) {
        this.THorarios = THorarios;
    }

    public Date getFecHasta() {
        return this.fecHasta;
    }

    public void setFecHasta(Date fecHasta) {
        this.fecHasta = fecHasta;
    }

    public Date getFecDesde() {
        return this.fecDesde;
    }

    public void setFecDesde(Date fecDesde) {
        this.fecDesde = fecDesde;
    }

    public boolean isVigente(Date tiempo) {
        if (tiempo.compareTo(this.getFecDesde()) >= 0 & (this.getFecHasta() == null || tiempo.compareTo(this.getFecHasta()) <= 0)) {
            return true;
        }
        return false;
    }

    public int compareTo(AsignacionesHorario o) {
        return this.getFecHasta().compareTo(o.getFecHasta());
    }
}
