package Negocio.Administracion;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import Negocio.Administracion.Cobro;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TCheques generated by hbm2java
 */
@Entity
@Table(name="T_CHEQUES"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class Cheque  implements java.io.Serializable {


     private int idCheque;
     private Date fecEmision;
     private Date fecVencimiento;
     private BigDecimal monto;
     private String nombreBanco;
     private int nroSucursal;
     
    public Cheque() {
    }

	
    public Cheque(int idCheque, Date fecEmision, Date fecVencimiento, BigDecimal monto, String nombreBanco, int nroSucursal) {
        this.idCheque = idCheque;
        this.fecEmision = fecEmision;
        this.fecVencimiento = fecVencimiento;
        this.monto = monto;
        this.nombreBanco = nombreBanco;
        this.nroSucursal = nroSucursal;
    }
    
   
     @Id 
    
    @Column(name="ID_CHEQUE", unique=true, nullable=false, precision=5, scale=0)
    public int getIdCheque() {
        return this.idCheque;
    }
    
    public void setIdCheque(int idCheque) {
        this.idCheque = idCheque;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_EMISION", nullable=false, length=23)
    public Date getFecEmision() {
        return this.fecEmision;
    }
    
    public void setFecEmision(Date fecEmision) {
        this.fecEmision = fecEmision;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_VENCIMIENTO", nullable=false, length=23)
    public Date getFecVencimiento() {
        return this.fecVencimiento;
    }
    
    public void setFecVencimiento(Date fecVencimiento) {
        this.fecVencimiento = fecVencimiento;
    }
    
    @Column(name="MONTO", nullable=false, precision=6, scale=4)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    
    @Column(name="NOMBRE_BANCO", nullable=false, length=50)
    public String getNombreBanco() {
        return this.nombreBanco;
    }
    
    public void setNombreBanco(String nombreBanco) {
        this.nombreBanco = nombreBanco;
    }
    
    @Column(name="NRO_SUCURSAL", nullable=false, precision=5, scale=0)
    public int getNroSucursal() {
        return this.nroSucursal;
    }
    
    public void setNroSucursal(int nroSucursal) {
        this.nroSucursal = nroSucursal;
    }




}


