package Negocio.Ventas;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import Negocio.Produccion.Producto;
import Negocio.Administracion.DetalleFactura;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TDetallesPedido generated by hbm2java
 */
@Entity
@Table(name="T_DETALLES_PEDIDO"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class DetallePedido  implements java.io.Serializable {


     private int idDetallePedido;
     private Pedido TPedidos;
     private Producto TProductos;
     private int cantidad;
     private BigDecimal precio;
     private Set<DetalleFactura> TDetallesFacturas = new HashSet<DetalleFactura>(0);

    public DetallePedido() {
    }

	
    public DetallePedido(int idDetallePedido, Pedido TPedidos, Producto TProductos, int cantidad, BigDecimal precio) {
        this.idDetallePedido = idDetallePedido;
        this.TPedidos = TPedidos;
        this.TProductos = TProductos;
        this.cantidad = cantidad;
        this.precio = precio;
    }
    public DetallePedido(int idDetallePedido, Pedido TPedidos, Producto TProductos, int cantidad, BigDecimal precio, Set<DetalleFactura> TDetallesFacturas) {
       this.idDetallePedido = idDetallePedido;
       this.TPedidos = TPedidos;
       this.TProductos = TProductos;
       this.cantidad = cantidad;
       this.precio = precio;
       this.TDetallesFacturas = TDetallesFacturas;
    }
   
     @Id 
    
    @Column(name="ID_DETALLE_PEDIDO", unique=true, nullable=false, precision=8, scale=0)
    public int getIdDetallePedido() {
        return this.idDetallePedido;
    }
    
    public void setIdDetallePedido(int idDetallePedido) {
        this.idDetallePedido = idDetallePedido;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PEDIDO", nullable=false)
    public Pedido getTPedidos() {
        return this.TPedidos;
    }
    
    public void setTPedidos(Pedido TPedidos) {
        this.TPedidos = TPedidos;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PRODUCTO", nullable=false)
    public Producto getTProductos() {
        return this.TProductos;
    }
    
    public void setTProductos(Producto TProductos) {
        this.TProductos = TProductos;
    }
    
    @Column(name="CANTIDAD", nullable=false, precision=5, scale=0)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    
    @Column(name="PRECIO", nullable=false, precision=6)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TDetallesPedido")
    public Set<DetalleFactura> getTDetallesFacturas() {
        return this.TDetallesFacturas;
    }
    
    public void setTDetallesFacturas(Set<DetalleFactura> TDetallesFacturas) {
        this.TDetallesFacturas = TDetallesFacturas;
    }




}


