package Negocio.Ventas;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import Negocio.Produccion.PlanProduccion;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPedidos generated by hbm2java
 */
@Entity
@Table(name="T_PEDIDOS"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class Pedido  implements java.io.Serializable {


     private int idPedido;
     private TipoPedido TTpedido;
     private Cliente TClientes;
     private EstadoPedido TEpedido;
     private Boolean entregaMaterial;
     private Date fecHoraEstimadaEntrega;
     private Date fecHoraGeneracion;
     private Date fecHoraRealEntrega;
     private Date fecSolicitada;
     private byte prioridad;
     private Set<PlanProduccion> TPlanesProduccions = new HashSet<PlanProduccion>(0);
     private Set<DetallePedido> TDetallesPedidos = new HashSet<DetallePedido>(0);

    public Pedido() {
    }

	
    public Pedido(int idPedido, TipoPedido TTpedido, Cliente TClientes, EstadoPedido TEpedido, Date fecHoraEstimadaEntrega, Date fecHoraGeneracion, Date fecHoraRealEntrega, Date fecSolicitada, byte prioridad) {
        this.idPedido = idPedido;
        this.TTpedido = TTpedido;
        this.TClientes = TClientes;
        this.TEpedido = TEpedido;
        this.fecHoraEstimadaEntrega = fecHoraEstimadaEntrega;
        this.fecHoraGeneracion = fecHoraGeneracion;
        this.fecHoraRealEntrega = fecHoraRealEntrega;
        this.fecSolicitada = fecSolicitada;
        this.prioridad = prioridad;
    }
    public Pedido(int idPedido, TipoPedido TTpedido, Cliente TClientes, EstadoPedido TEpedido, Boolean entregaMaterial, Date fecHoraEstimadaEntrega, Date fecHoraGeneracion, Date fecHoraRealEntrega, Date fecSolicitada, byte prioridad, Set<PlanProduccion> TPlanesProduccions, Set<DetallePedido> TDetallesPedidos) {
       this.idPedido = idPedido;
       this.TTpedido = TTpedido;
       this.TClientes = TClientes;
       this.TEpedido = TEpedido;
       this.entregaMaterial = entregaMaterial;
       this.fecHoraEstimadaEntrega = fecHoraEstimadaEntrega;
       this.fecHoraGeneracion = fecHoraGeneracion;
       this.fecHoraRealEntrega = fecHoraRealEntrega;
       this.fecSolicitada = fecSolicitada;
       this.prioridad = prioridad;
       this.TPlanesProduccions = TPlanesProduccions;
       this.TDetallesPedidos = TDetallesPedidos;
    }
   
     @Id 
    
    @Column(name="ID_PEDIDO", unique=true, nullable=false, precision=8, scale=0)
    public int getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TPEDIDO", nullable=false)
    public TipoPedido getTTpedido() {
        return this.TTpedido;
    }
    
    public void setTTpedido(TipoPedido TTpedido) {
        this.TTpedido = TTpedido;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CLIENTE", nullable=false)
    public Cliente getTClientes() {
        return this.TClientes;
    }
    
    public void setTClientes(Cliente TClientes) {
        this.TClientes = TClientes;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_EPEDIDO", nullable=false)
    public EstadoPedido getTEpedido() {
        return this.TEpedido;
    }
    
    public void setTEpedido(EstadoPedido TEpedido) {
        this.TEpedido = TEpedido;
    }
    
    @Column(name="ENTREGA_MATERIAL")
    public Boolean getEntregaMaterial() {
        return this.entregaMaterial;
    }
    
    public void setEntregaMaterial(Boolean entregaMaterial) {
        this.entregaMaterial = entregaMaterial;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_HORA_ESTIMADA_ENTREGA", nullable=false, length=23)
    public Date getFecHoraEstimadaEntrega() {
        return this.fecHoraEstimadaEntrega;
    }
    
    public void setFecHoraEstimadaEntrega(Date fecHoraEstimadaEntrega) {
        this.fecHoraEstimadaEntrega = fecHoraEstimadaEntrega;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_HORA_GENERACION", nullable=false, length=23)
    public Date getFecHoraGeneracion() {
        return this.fecHoraGeneracion;
    }
    
    public void setFecHoraGeneracion(Date fecHoraGeneracion) {
        this.fecHoraGeneracion = fecHoraGeneracion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_HORA_REAL_ENTREGA", nullable=false, length=23)
    public Date getFecHoraRealEntrega() {
        return this.fecHoraRealEntrega;
    }
    
    public void setFecHoraRealEntrega(Date fecHoraRealEntrega) {
        this.fecHoraRealEntrega = fecHoraRealEntrega;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_SOLICITADA", nullable=false, length=23)
    public Date getFecSolicitada() {
        return this.fecSolicitada;
    }
    
    public void setFecSolicitada(Date fecSolicitada) {
        this.fecSolicitada = fecSolicitada;
    }
    
    @Column(name="PRIORIDAD", nullable=false, precision=2, scale=0)
    public byte getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(byte prioridad) {
        this.prioridad = prioridad;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TPedidos")
    public Set<PlanProduccion> getTPlanesProduccions() {
        return this.TPlanesProduccions;
    }
    
    public void setTPlanesProduccions(Set<PlanProduccion> TPlanesProduccions) {
        this.TPlanesProduccions = TPlanesProduccions;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TPedidos")
    public Set<DetallePedido> getTDetallesPedidos() {
        return this.TDetallesPedidos;
    }
    
    public void setTDetallesPedidos(Set<DetallePedido> TDetallesPedidos) {
        this.TDetallesPedidos = TDetallesPedidos;
    }




}


