package Negocio.Ventas;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TTpedido generated by hbm2java
 */
@Entity
@Table(name="T_TPEDIDO"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class TipoPedido  implements java.io.Serializable {


     private byte idTpedido;
     private String nombre;
     private String descripcion;
     private Set<Pedido> TPedidoses = new HashSet<Pedido>(0);

    public TipoPedido() {
    }

	
    public TipoPedido(byte idTpedido, String nombre) {
        this.idTpedido = idTpedido;
        this.nombre = nombre;
    }
    public TipoPedido(byte idTpedido, String nombre, String descripcion, Set<Pedido> TPedidoses) {
       this.idTpedido = idTpedido;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.TPedidoses = TPedidoses;
    }
   
     @Id 
    
    @Column(name="ID_TPEDIDO", unique=true, nullable=false, precision=2, scale=0)
    public byte getIdTpedido() {
        return this.idTpedido;
    }
    
    public void setIdTpedido(byte idTpedido) {
        this.idTpedido = idTpedido;
    }
    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="DESCRIPCION", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TTpedido")
    public Set<Pedido> getTPedidoses() {
        return this.TPedidoses;
    }
    
    public void setTPedidoses(Set<Pedido> TPedidoses) {
        this.TPedidoses = TPedidoses;
    }




}


