package Negocio.Ventas;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TTcliente generated by hbm2java
 */
@Entity
@Table(name="T_TCLIENTE"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class TipoCliente  implements java.io.Serializable {


     private int idTcliente;
     private String nombre;
     private String descripcion;
     private Set<Cliente> TClienteses = new HashSet<Cliente>(0);

    public TipoCliente() {
    }

	
    public TipoCliente(int idTcliente, String nombre) {
        this.idTcliente = idTcliente;
        this.nombre = nombre;
    }
    public TipoCliente(int idTcliente, String nombre, String descripcion, Set<Cliente> TClienteses) {
       this.idTcliente = idTcliente;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.TClienteses = TClienteses;
    }
   
     @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_TCLIENTE", unique=true, nullable=false, precision=2, scale=0)
    public int getIdTcliente() {
        return this.idTcliente;
    }
    
    private void setIdTcliente(int idTcliente) {
        this.idTcliente = idTcliente;
    }
    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    private void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="DESCRIPCION", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TTcliente")
    public Set<Cliente> getTClienteses() {
        return this.TClienteses;
    }
    
    public void setTClienteses(Set<Cliente> TClienteses) {
        this.TClienteses = TClienteses;
    }




}


