/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaPlanProduccionPrincipal.java
 *
 * Created on 17-ago-2012, 23:35:12
 */
package Presentacion.Produccion;

import BaseDeDatos.HibernateUtil;
import BaseDeDatos.Ventas.PedidoBD;
import Negocio.Produccion.PlanProduccion;
import Negocio.Produccion.Planificacion.GanttManager;
import Presentacion.Mensajes;
import Presentacion.TablaManager;
import Presentacion.Utilidades;
import java.util.Vector;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.hibernate.Hibernate;
import org.jfree.ui.ApplicationFrame;

/**
 *
 * @author Rodrigo
 */
public class PantallaPlanProduccionPrincipal extends javax.swing.JDialog {

    /** Creates new form PantallaPlanProduccionPrincipal */
    private TablaManager<PlanProduccion> tmPlan;

    public PantallaPlanProduccionPrincipal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tmPlan = new TablaManager<PlanProduccion>(tbPlan) {

            @Override
            public Vector ObjetoFila(PlanProduccion elemento) {
                Vector salida = new Vector();
                String aux = "";
                salida.add(elemento.getPedido().getIdPedido());
                salida.add(elemento.getPedido().getCliente().getRazonSocial());
                salida.add(elemento.getPedido().getCliente().getCuit());
                salida.add(Utilidades.parseFecha(elemento.getFecGeneracion()));
                salida.add(elemento.getPedido().getPrioridadTexto());
                salida.add(Utilidades.parseFecha(elemento.getFecHoraPrevistaInicio()));
                salida.add(Utilidades.parseFecha(elemento.getFecHoraPrevistaFin()));
                salida.add(elemento.getEstado().getNombre());
                return salida;
            }

            @Override
            public Vector getCabecera() {
                Vector salida = new Vector();
                salida.add("Nro");
                salida.add("Razon Social");
                salida.add("CUIT");
                salida.add("Generacion Plan");
                salida.add("Prioridad");
                salida.add("Fecha Inicio Prevista");
                salida.add("Fecha Fin Prevista");
                salida.add("Estado");
                return salida;
            }
        };
        actualizar();
    }

    public void actualizar() {
        tmPlan.setDatos(HibernateUtil.ejecutarConsulta("FROM PlanProduccion"));
        if (tmPlan.getSize() == 0) {
            lblMensaje.setText("No se encontró ningún plan vigente.");
        } else if (tmPlan.getSize() == 1) {
            lblMensaje.setText("Se encontró un plan vigente.");
        } else if (tmPlan.getSize() == 1) {
            lblMensaje.setText("Se encontró " + tmPlan.getSize() + " planes vigentes.");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPlanes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPlan = new javax.swing.JTable();
        btnPlanificar = new javax.swing.JButton();
        btnPlanificar1 = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Planes de Produccion");

        pnlPlanes.setBorder(javax.swing.BorderFactory.createTitledBorder("Planes de Produccion Vigentes"));

        tbPlan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro", "Razon Social", "CUIT", "F. Generacion", "Prioridad", "Fecha Inicio Prevista/Real", "Fecha Fin Prevista", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tbPlan);

        btnPlanificar.setText("<html><center>Generar<br>Plan</center></html>");
        btnPlanificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanificarActionPerformed(evt);
            }
        });

        btnPlanificar1.setText("<html><center>Modificar<br>Plan</center></html>");
        btnPlanificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanificar1ActionPerformed(evt);
            }
        });

        lblMensaje.setText("XXX");

        jButton1.setText("Gantt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPlanesLayout = new javax.swing.GroupLayout(pnlPlanes);
        pnlPlanes.setLayout(pnlPlanesLayout);
        pnlPlanesLayout.setHorizontalGroup(
            pnlPlanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlanesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPlanesLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlPlanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addGroup(pnlPlanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnPlanificar, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(btnPlanificar1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))))
                    .addComponent(lblMensaje))
                .addContainerGap())
        );
        pnlPlanesLayout.setVerticalGroup(
            pnlPlanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlanesLayout.createSequentialGroup()
                .addGroup(pnlPlanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPlanesLayout.createSequentialGroup()
                        .addComponent(btnPlanificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPlanificar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje))
        );

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlPlanes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPlanes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlanificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanificarActionPerformed
        // TODO add your handling code here:
        PantallaPlanProduccionNuevo.generarNuevoPlan(this);
        actualizar();
    }//GEN-LAST:event_btnPlanificarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnPlanificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanificar1ActionPerformed
        // TODO add your handling code here:
        if (tmPlan.getSeletedObject() == null) {
            Mensajes.mensajeErrorGenerico("Debe elegir un plan.");
            return;
        }
        PantallaPlanProduccionNuevo.ModificarPlan(this, tmPlan.getSeletedObject());
        actualizar();
    }//GEN-LAST:event_btnPlanificar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (tmPlan.getSeletedObject() != null) {
            GanttManager.getFrameGantt("Gantt", tmPlan.getSeletedObject(),this).setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                PantallaPlanProduccionPrincipal dialog = new PantallaPlanProduccionPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlanificar;
    private javax.swing.JButton btnPlanificar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JPanel pnlPlanes;
    private javax.swing.JTable tbPlan;
    // End of variables declaration//GEN-END:variables
}
