package Presentacion;


import BaseDeDatos.HibernateUtil;
import Negocio.Ventas.Cliente;
import Presentacion.Ventas.PantallaClienteABM;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BuscadorCliente.java
 *
 * Created on 18/08/2011, 11:53:03
 */
/**
 *
 * @author Rodrigo
 */
public class BuscadorCliente extends javax.swing.JPanel {

    /** Creates new form BuscadorCliente */
    private Cliente cliente;

    public BuscadorCliente() {
        initComponents();
        cmbBuscar.setVisible(true);
        txtBuscar.setVisible(true);
    }

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente c)
    {
        ArrayList<Cliente> lst=new ArrayList<Cliente>();
        lst.add(c);
        cargarCombo(lst);
        cmbBuscar.setSelectedIndex(0);
    }

    private void cargarCombo(List<Cliente> lst) {
        cmbBuscar.setPopupVisible(false);

        DefaultComboBoxModel model=new DefaultComboBoxModel();
        for(Cliente c:lst)
            model.addElement(new Item(c));

        cmbBuscar.setModel(model);
        pnlBuscador.repaint();
    }

    @Override
    public void setEnabled(boolean enabled) {
       
        txtBuscar.setEditable(enabled);
        rdbCUIL.setEnabled(enabled);
        rdbRazonSocial.setEnabled(enabled);
        super.setEnabled(enabled);
    }


    private class Item {

        public Cliente cliente;

        public Item(Cliente c) {
            cliente = c;
        }

        @Override
        public String toString() {
            if (rdbCUIL.isSelected()) {
                return cliente.getCuit() + " | " + cliente.getRazonSocial();
            }
            if (rdbRazonSocial.isSelected()) {
                return cliente.getRazonSocial();
            }
            return "---";
        }
    }

    private void iniciarBusqueda() {
        String valor = txtBuscar.getText().trim();
        String atributo = "";

        if (rdbCUIL.isSelected()) {
            atributo = "cuil";
        }
        if (rdbRazonSocial.isSelected()) {
            atributo = "razonSocial";
        }

        String HQL = String.format("from Cliente as c where LOWER(c.%s) like LOWER('%s%%')", atributo, valor);
        List<Cliente> lst = HibernateUtil.ejecutarConsulta(HQL);
        cargarCombo(lst);
    }

    private void mostrarMenu() {       
        if (cmbBuscar.getItemCount() > 0) {
            cmbBuscar.showPopup();
        } else {
            cmbBuscar.hidePopup();
        }
         cmbBuscar.setSelectedIndex(-1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgBusqueda = new javax.swing.ButtonGroup();
        pnlBuscador = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        cmbBuscar = new javax.swing.JComboBox();
        rdbCUIL = new javax.swing.JRadioButton();
        rdbRazonSocial = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCUIL = new javax.swing.JTextField();
        txtRazonSocial = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        pnlBuscador.setLayout(new java.awt.CardLayout());
        pnlBuscador.setPreferredSize(txtBuscar.getSize());

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        pnlBuscador.add(txtBuscar, "card2");

        cmbBuscar.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbBuscarPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBuscarActionPerformed(evt);
            }
        });
        pnlBuscador.add(cmbBuscar, "card3");

        btgBusqueda.add(rdbCUIL);
        rdbCUIL.setFont(new java.awt.Font("Tahoma", 1, 11));
        rdbCUIL.setText("CUIL"); // NOI18N
        rdbCUIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCUILActionPerformed(evt);
            }
        });

        btgBusqueda.add(rdbRazonSocial);
        rdbRazonSocial.setFont(new java.awt.Font("Tahoma", 1, 11));
        rdbRazonSocial.setSelected(true);
        rdbRazonSocial.setText("Razón Social"); // NOI18N
        rdbRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbRazonSocialActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("CUIL:"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Razón Social:"); // NOI18N

        txtCUIL.setEditable(false);

        txtRazonSocial.setEditable(false);

        jButton1.setText("Nuevo Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlBuscador, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbRazonSocial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbCUIL)
                        .addGap(77, 77, 77)
                        .addComponent(jButton1))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCUIL, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRazonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdbRazonSocial)
                        .addComponent(rdbCUIL)
                        .addComponent(jButton1))
                    .addComponent(pnlBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCUIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            return;

         iniciarBusqueda();
        mostrarMenu();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void cmbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBuscarActionPerformed
        // TODO add your handling code here:
        if (cmbBuscar.getSelectedIndex() < 0) {
            return;
        }
        cliente = ((Item) cmbBuscar.getSelectedItem()).cliente;
        txtCUIL.setText(""+cliente.getCuit());
        txtRazonSocial.setText(""+cliente.getRazonSocial());

        if (rdbCUIL.isSelected()) 
            txtBuscar.setText(cliente.getCuit() + "");
        
        if (rdbRazonSocial.isSelected()) 
            txtBuscar.setText(cliente.getRazonSocial() + "");
        
        pnlBuscador.repaint();
}//GEN-LAST:event_cmbBuscarActionPerformed

    private void cmbBuscarPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbBuscarPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
         txtBuscar.requestFocus();
        pnlBuscador.repaint();
    }//GEN-LAST:event_cmbBuscarPopupMenuWillBecomeInvisible

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
        if(cmbBuscar.isPopupVisible())
        {
            if(evt.getKeyCode()==KeyEvent.VK_DOWN)
            {
                cmbBuscar.requestFocus();
                cmbBuscar.setSelectedIndex(0);
                return;
            }
            if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            {
                cmbBuscar.requestFocus();
                cmbBuscar.setSelectedIndex(0);
                cmbBuscar.setVisible(false);
                cmbBuscar.setVisible(true);
                txtBuscar.requestFocus();
                pnlBuscador.repaint();
                return;
            }
        }
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            iniciarBusqueda();
            mostrarMenu();
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void rdbRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbRazonSocialActionPerformed
        // TODO add your handling code here:
        txtBuscar.requestFocus();
    }//GEN-LAST:event_rdbRazonSocialActionPerformed

    private void rdbCUILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCUILActionPerformed
        // TODO add your handling code here:
           txtBuscar.requestFocus();
    }//GEN-LAST:event_rdbCUILActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PantallaClienteABM.iniciarClienteAlta(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgBusqueda;
    private javax.swing.JComboBox cmbBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlBuscador;
    private javax.swing.JRadioButton rdbCUIL;
    private javax.swing.JRadioButton rdbRazonSocial;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCUIL;
    private javax.swing.JTextField txtRazonSocial;
    // End of variables declaration//GEN-END:variables
}
