package BaseDeDatos.UbicacionGeografica;
// Generated 09/08/2011 13:12:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TBarrios generated by hbm2java
 */
public class TBarrios  implements java.io.Serializable {


     private short idBarrio;
     private TLocalidades TLocalidades;
     private String nombre;
     private String descripcion;
     private Set TDomicilioses = new HashSet(0);

    public TBarrios() {
    }

	
    public TBarrios(short idBarrio, TLocalidades TLocalidades, String nombre) {
        this.idBarrio = idBarrio;
        this.TLocalidades = TLocalidades;
        this.nombre = nombre;
    }
    public TBarrios(short idBarrio, TLocalidades TLocalidades, String nombre, String descripcion, Set TDomicilioses) {
       this.idBarrio = idBarrio;
       this.TLocalidades = TLocalidades;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.TDomicilioses = TDomicilioses;
    }
   
    public short getIdBarrio() {
        return this.idBarrio;
    }
    
    public void setIdBarrio(short idBarrio) {
        this.idBarrio = idBarrio;
    }
    public TLocalidades getTLocalidades() {
        return this.TLocalidades;
    }
    
    public void setTLocalidades(TLocalidades TLocalidades) {
        this.TLocalidades = TLocalidades;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getTDomicilioses() {
        return this.TDomicilioses;
    }
    
    public void setTDomicilioses(Set TDomicilioses) {
        this.TDomicilioses = TDomicilioses;
    }




}


