package Negocio.Compras;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import Negocio.Deposito.Faltante;
import Negocio.Produccion.DetalleEtapaProduccion;
import Negocio.Compras.DetalleOrdenCompra;
import Negocio.Produccion.DetalleProducto;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TMateriales generated by hbm2java
 */
@Entity
@Table(name="T_MATERIALES"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class Material  implements java.io.Serializable {


     private short idMaterial;
     private String nombre;
     private String descripcion;
     private Integer diametro;
     private boolean esMateriaPrima;
     private Short logitud;
     private Date fecBaja;
     private String motivoBaja;
     private short stockActual;
     private short stockMinimo;
     private short stockReservado;
     private String codigo;
     private Set<DetalleProducto> TDetallesProductos = new HashSet<DetalleProducto>(0);
     private Set<DetalleEtapaProduccion> TDetallesEtapas = new HashSet<DetalleEtapaProduccion>(0);
     private Set<MaterialesXProveedor> TMaterialesXProveedors = new HashSet<MaterialesXProveedor>(0);
     private Set<Faltante> TFaltanteses = new HashSet<Faltante>(0);
     private Set<DetalleOrdenCompra> TDetallesOrdenCompras = new HashSet<DetalleOrdenCompra>(0);

    public Material() {
    }

	
    public Material(short idMaterial, String nombre, boolean esMateriaPrima, short stockActual, short stockMinimo, short stockReservado, String codigo) {
        this.idMaterial = idMaterial;
        this.nombre = nombre;
        this.esMateriaPrima = esMateriaPrima;
        this.stockActual = stockActual;
        this.stockMinimo = stockMinimo;
        this.stockReservado = stockReservado;
        this.codigo = codigo;
    }
    public Material(short idMaterial, String nombre, String descripcion, Integer diametro, boolean esMateriaPrima, Short logitud, Date fecBaja, String motivoBaja, short stockActual, short stockMinimo, short stockReservado, String codigo, Set<DetalleProducto> TDetallesProductos, Set<DetalleEtapaProduccion> TDetallesEtapas, Set<MaterialesXProveedor> TMaterialesXProveedors, Set<Faltante> TFaltanteses, Set<DetalleOrdenCompra> TDetallesOrdenCompras) {
       this.idMaterial = idMaterial;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.diametro = diametro;
       this.esMateriaPrima = esMateriaPrima;
       this.logitud = logitud;
       this.fecBaja = fecBaja;
       this.motivoBaja = motivoBaja;
       this.stockActual = stockActual;
       this.stockMinimo = stockMinimo;
       this.stockReservado = stockReservado;
       this.codigo = codigo;
       this.TDetallesProductos = TDetallesProductos;
       this.TDetallesEtapas = TDetallesEtapas;
       this.TMaterialesXProveedors = TMaterialesXProveedors;
       this.TFaltanteses = TFaltanteses;
       this.TDetallesOrdenCompras = TDetallesOrdenCompras;
    }
   
     @Id 
    
    @Column(name="ID_MATERIAL", unique=true, nullable=false, precision=3, scale=0)
    public short getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(short idMaterial) {
        this.idMaterial = idMaterial;
    }
    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="DESCRIPCION", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="DIAMETRO", precision=6, scale=0)
    public Integer getDiametro() {
        return this.diametro;
    }
    
    public void setDiametro(Integer diametro) {
        this.diametro = diametro;
    }
    
    @Column(name="ES_MATERIA_PRIMA", nullable=false)
    public boolean isEsMateriaPrima() {
        return this.esMateriaPrima;
    }
    
    public void setEsMateriaPrima(boolean esMateriaPrima) {
        this.esMateriaPrima = esMateriaPrima;
    }
    
    @Column(name="LOGITUD", precision=3, scale=0)
    public Short getLogitud() {
        return this.logitud;
    }
    
    public void setLogitud(Short logitud) {
        this.logitud = logitud;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_BAJA", length=23)
    public Date getFecBaja() {
        return this.fecBaja;
    }
    
    public void setFecBaja(Date fecBaja) {
        this.fecBaja = fecBaja;
    }
    
    @Column(name="MOTIVO_BAJA", length=200)
    public String getMotivoBaja() {
        return this.motivoBaja;
    }
    
    public void setMotivoBaja(String motivoBaja) {
        this.motivoBaja = motivoBaja;
    }
    
    @Column(name="STOCK_ACTUAL", nullable=false, precision=3, scale=0)
    public short getStockActual() {
        return this.stockActual;
    }
    
    public void setStockActual(short stockActual) {
        this.stockActual = stockActual;
    }
    
    @Column(name="STOCK_MINIMO", nullable=false, precision=3, scale=0)
    public short getStockMinimo() {
        return this.stockMinimo;
    }
    
    public void setStockMinimo(short stockMinimo) {
        this.stockMinimo = stockMinimo;
    }
    
    @Column(name="STOCK_RESERVADO", nullable=false, precision=3, scale=0)
    public short getStockReservado() {
        return this.stockReservado;
    }
    
    public void setStockReservado(short stockReservado) {
        this.stockReservado = stockReservado;
    }
    
    @Column(name="CODIGO", nullable=false, length=2)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TMateriales")
    public Set<DetalleProducto> getTDetallesProductos() {
        return this.TDetallesProductos;
    }
    
    public void setTDetallesProductos(Set<DetalleProducto> TDetallesProductos) {
        this.TDetallesProductos = TDetallesProductos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TMateriales")
    public Set<DetalleEtapaProduccion> getTDetallesEtapas() {
        return this.TDetallesEtapas;
    }
    
    public void setTDetallesEtapas(Set<DetalleEtapaProduccion> TDetallesEtapas) {
        this.TDetallesEtapas = TDetallesEtapas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TMateriales")
    public Set<MaterialesXProveedor> getTMaterialesXProveedors() {
        return this.TMaterialesXProveedors;
    }
    
    public void setTMaterialesXProveedors(Set<MaterialesXProveedor> TMaterialesXProveedors) {
        this.TMaterialesXProveedors = TMaterialesXProveedors;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TMateriales")
    public Set<Faltante> getTFaltanteses() {
        return this.TFaltanteses;
    }
    
    public void setTFaltanteses(Set<Faltante> TFaltanteses) {
        this.TFaltanteses = TFaltanteses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TMateriales")
    public Set<DetalleOrdenCompra> getTDetallesOrdenCompras() {
        return this.TDetallesOrdenCompras;
    }
    
    public void setTDetallesOrdenCompras(Set<DetalleOrdenCompra> TDetallesOrdenCompras) {
        this.TDetallesOrdenCompras = TDetallesOrdenCompras;
    }




}


