package Negocio.Compras;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import Negocio.Compras.DetalleOrdenCompra;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOrdenesCompra generated by hbm2java
 */
@Entity
@Table(name="T_ORDENES_COMPRA"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class OrdenCompra  implements java.io.Serializable {


     private int idOrdenCompra;
     private Proveedor TProveedores;
     private EstadoOrdenCompra TEordenCompra;
     private String codigo;
     private Date fecGeneracion;
     private Date fecRecepcion;
     private Set<DetalleOrdenCompra> TDetallesOrdenCompras = new HashSet<DetalleOrdenCompra>(0);
     private Set<Reclamo> TReclamoses = new HashSet<Reclamo>(0);

    public OrdenCompra() {
    }

	
    public OrdenCompra(int idOrdenCompra, Proveedor TProveedores, EstadoOrdenCompra TEordenCompra, String codigo, Date fecGeneracion, Date fecRecepcion) {
        this.idOrdenCompra = idOrdenCompra;
        this.TProveedores = TProveedores;
        this.TEordenCompra = TEordenCompra;
        this.codigo = codigo;
        this.fecGeneracion = fecGeneracion;
        this.fecRecepcion = fecRecepcion;
    }
    public OrdenCompra(int idOrdenCompra, Proveedor TProveedores, EstadoOrdenCompra TEordenCompra, String codigo, Date fecGeneracion, Date fecRecepcion, Set<DetalleOrdenCompra> TDetallesOrdenCompras, Set<Reclamo> TReclamoses) {
       this.idOrdenCompra = idOrdenCompra;
       this.TProveedores = TProveedores;
       this.TEordenCompra = TEordenCompra;
       this.codigo = codigo;
       this.fecGeneracion = fecGeneracion;
       this.fecRecepcion = fecRecepcion;
       this.TDetallesOrdenCompras = TDetallesOrdenCompras;
       this.TReclamoses = TReclamoses;
    }
   
     @Id 
    
    @Column(name="ID_ORDEN_COMPRA", unique=true, nullable=false, precision=8, scale=0)
    public int getIdOrdenCompra() {
        return this.idOrdenCompra;
    }
    
    public void setIdOrdenCompra(int idOrdenCompra) {
        this.idOrdenCompra = idOrdenCompra;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PROVEEDOR", nullable=false)
    public Proveedor getTProveedores() {
        return this.TProveedores;
    }
    
    public void setTProveedores(Proveedor TProveedores) {
        this.TProveedores = TProveedores;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_EORDEN_COMPRA", nullable=false)
    public EstadoOrdenCompra getTEordenCompra() {
        return this.TEordenCompra;
    }
    
    public void setTEordenCompra(EstadoOrdenCompra TEordenCompra) {
        this.TEordenCompra = TEordenCompra;
    }
    
    @Column(name="CODIGO", nullable=false, length=2)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_GENERACION", nullable=false, length=23)
    public Date getFecGeneracion() {
        return this.fecGeneracion;
    }
    
    public void setFecGeneracion(Date fecGeneracion) {
        this.fecGeneracion = fecGeneracion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FEC_RECEPCION", nullable=false, length=23)
    public Date getFecRecepcion() {
        return this.fecRecepcion;
    }
    
    public void setFecRecepcion(Date fecRecepcion) {
        this.fecRecepcion = fecRecepcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TOrdenesCompra")
    public Set<DetalleOrdenCompra> getTDetallesOrdenCompras() {
        return this.TDetallesOrdenCompras;
    }
    
    public void setTDetallesOrdenCompras(Set<DetalleOrdenCompra> TDetallesOrdenCompras) {
        this.TDetallesOrdenCompras = TDetallesOrdenCompras;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TOrdenesCompra")
    public Set<Reclamo> getTReclamoses() {
        return this.TReclamoses;
    }
    
    public void setTReclamoses(Set<Reclamo> TReclamoses) {
        this.TReclamoses = TReclamoses;
    }




}


