package BaseDeDatos;
// Generated 09/08/2011 13:12:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TAsistenciasEmpleado generated by hbm2java
 */
public class TAsistenciasEmpleado  implements java.io.Serializable {


     private short idAsistenciaEmpleado;
     private TEmpleados TEmpleados;
     private Date fecAsistencia;
     private String horaIngreso;
     private Date fecEgreso;
     private String observaciones;

    public TAsistenciasEmpleado() {
    }

	
    public TAsistenciasEmpleado(short idAsistenciaEmpleado, TEmpleados TEmpleados, Date fecAsistencia, String horaIngreso) {
        this.idAsistenciaEmpleado = idAsistenciaEmpleado;
        this.TEmpleados = TEmpleados;
        this.fecAsistencia = fecAsistencia;
        this.horaIngreso = horaIngreso;
    }
    public TAsistenciasEmpleado(short idAsistenciaEmpleado, TEmpleados TEmpleados, Date fecAsistencia, String horaIngreso, Date fecEgreso, String observaciones) {
       this.idAsistenciaEmpleado = idAsistenciaEmpleado;
       this.TEmpleados = TEmpleados;
       this.fecAsistencia = fecAsistencia;
       this.horaIngreso = horaIngreso;
       this.fecEgreso = fecEgreso;
       this.observaciones = observaciones;
    }
   
    public short getIdAsistenciaEmpleado() {
        return this.idAsistenciaEmpleado;
    }
    
    public void setIdAsistenciaEmpleado(short idAsistenciaEmpleado) {
        this.idAsistenciaEmpleado = idAsistenciaEmpleado;
    }
    public TEmpleados getTEmpleados() {
        return this.TEmpleados;
    }
    
    public void setTEmpleados(TEmpleados TEmpleados) {
        this.TEmpleados = TEmpleados;
    }
    public Date getFecAsistencia() {
        return this.fecAsistencia;
    }
    
    public void setFecAsistencia(Date fecAsistencia) {
        this.fecAsistencia = fecAsistencia;
    }
    public String getHoraIngreso() {
        return this.horaIngreso;
    }
    
    public void setHoraIngreso(String horaIngreso) {
        this.horaIngreso = horaIngreso;
    }
    public Date getFecEgreso() {
        return this.fecEgreso;
    }
    
    public void setFecEgreso(Date fecEgreso) {
        this.fecEgreso = fecEgreso;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


