package BaseDeDatos;
// Generated 09/08/2011 13:12:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TOrdenesCompra generated by hbm2java
 */
public class TOrdenesCompra  implements java.io.Serializable {


     private int idOrdenCompra;
     private TProveedores TProveedores;
     private TEordenCompra TEordenCompra;
     private String codigo;
     private Date fecGeneracion;
     private Date fecRecepcion;
     private Set TDetallesOrdenCompras = new HashSet(0);
     private Set TReclamoses = new HashSet(0);

    public TOrdenesCompra() {
    }

	
    public TOrdenesCompra(int idOrdenCompra, TProveedores TProveedores, TEordenCompra TEordenCompra, String codigo, Date fecGeneracion, Date fecRecepcion) {
        this.idOrdenCompra = idOrdenCompra;
        this.TProveedores = TProveedores;
        this.TEordenCompra = TEordenCompra;
        this.codigo = codigo;
        this.fecGeneracion = fecGeneracion;
        this.fecRecepcion = fecRecepcion;
    }
    public TOrdenesCompra(int idOrdenCompra, TProveedores TProveedores, TEordenCompra TEordenCompra, String codigo, Date fecGeneracion, Date fecRecepcion, Set TDetallesOrdenCompras, Set TReclamoses) {
       this.idOrdenCompra = idOrdenCompra;
       this.TProveedores = TProveedores;
       this.TEordenCompra = TEordenCompra;
       this.codigo = codigo;
       this.fecGeneracion = fecGeneracion;
       this.fecRecepcion = fecRecepcion;
       this.TDetallesOrdenCompras = TDetallesOrdenCompras;
       this.TReclamoses = TReclamoses;
    }
   
    public int getIdOrdenCompra() {
        return this.idOrdenCompra;
    }
    
    public void setIdOrdenCompra(int idOrdenCompra) {
        this.idOrdenCompra = idOrdenCompra;
    }
    public TProveedores getTProveedores() {
        return this.TProveedores;
    }
    
    public void setTProveedores(TProveedores TProveedores) {
        this.TProveedores = TProveedores;
    }
    public TEordenCompra getTEordenCompra() {
        return this.TEordenCompra;
    }
    
    public void setTEordenCompra(TEordenCompra TEordenCompra) {
        this.TEordenCompra = TEordenCompra;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Date getFecGeneracion() {
        return this.fecGeneracion;
    }
    
    public void setFecGeneracion(Date fecGeneracion) {
        this.fecGeneracion = fecGeneracion;
    }
    public Date getFecRecepcion() {
        return this.fecRecepcion;
    }
    
    public void setFecRecepcion(Date fecRecepcion) {
        this.fecRecepcion = fecRecepcion;
    }
    public Set getTDetallesOrdenCompras() {
        return this.TDetallesOrdenCompras;
    }
    
    public void setTDetallesOrdenCompras(Set TDetallesOrdenCompras) {
        this.TDetallesOrdenCompras = TDetallesOrdenCompras;
    }
    public Set getTReclamoses() {
        return this.TReclamoses;
    }
    
    public void setTReclamoses(Set TReclamoses) {
        this.TReclamoses = TReclamoses;
    }




}


