package Negocio.Web;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import Negocio.Ventas.Cliente;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TClientesWeb generated by hbm2java
 */
@Entity
@Table(name="T_CLIENTES_WEB"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class ClienteWeb  implements java.io.Serializable {


     private int idClienteWeb;
     private String usuario;
     private String contrasenia;
     private Set<Cliente> TClienteses = new HashSet<Cliente>(0);

    public ClienteWeb() {
    }

	
    public ClienteWeb(int idClienteWeb, String usuario, String contrasenia) {
        this.idClienteWeb = idClienteWeb;
        this.usuario = usuario;
        this.contrasenia = contrasenia;
    }
    public ClienteWeb(int idClienteWeb, String usuario, String contrasenia, Set<Cliente> TClienteses) {
       this.idClienteWeb = idClienteWeb;
       this.usuario = usuario;
       this.contrasenia = contrasenia;
       this.TClienteses = TClienteses;
    }
   
     @Id 
    
    @Column(name="ID_CLIENTE_WEB", unique=true, nullable=false, precision=5, scale=0)
    public int getIdClienteWeb() {
        return this.idClienteWeb;
    }
    
    public void setIdClienteWeb(int idClienteWeb) {
        this.idClienteWeb = idClienteWeb;
    }
    
    @Column(name="USUARIO", nullable=false, length=20)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    
    @Column(name="CONTRASENIA", nullable=false, length=20)
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TClientesWeb")
    public Set<Cliente> getTClienteses() {
        return this.TClienteses;
    }
    
    public void setTClienteses(Set<Cliente> TClienteses) {
        this.TClienteses = TClienteses;
    }




}


