package Negocio.UbicacionGeografica;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TBarrios generated by hbm2java
 */
@Entity
@Table(name = "T_BARRIOS", schema = "dbo", catalog = "Ramaty")
public class Barrio implements java.io.Serializable {

    @Id
    @GeneratedValue
    @Column(name = "ID_BARRIO", unique = true, nullable = false, precision = 3, scale = 0)
    private short idBarrio;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_LOCALIDAD", nullable = false)
    private Localidad TLocalidades;
    @Column(name = "NOMBRE", nullable = false, length = 50)
    private String nombre;
    @Column(name = "DESCRIPCION", length = 200)
    private String descripcion;

    public Barrio() {
    }

    public Barrio(short idBarrio, Localidad TLocalidades, String nombre) {
        this.idBarrio = idBarrio;
        this.TLocalidades = TLocalidades;
        this.nombre = nombre;
    }

    public Barrio(short idBarrio, Localidad TLocalidades, String nombre, String descripcion) {
        this.idBarrio = idBarrio;
        this.TLocalidades = TLocalidades;
        this.nombre = nombre;
        this.descripcion = descripcion;

    }

    public short getIdBarrio() {
        return this.idBarrio;
    }

    public void setIdBarrio(short idBarrio) {
        this.idBarrio = idBarrio;
    }

    public Localidad getTLocalidades() {
        return this.TLocalidades;
    }

    public void setTLocalidades(Localidad TLocalidades) {
        this.TLocalidades = TLocalidades;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Override
    public boolean equals(Object obj) {
        try{
        if(this.getNombre().toLowerCase().equals(((Barrio)obj).getNombre().toLowerCase()))
            return true;
        }catch(Exception e){}
        return false;
    }

    @Override
    public String toString() {
        return this.getNombre();
    }
}
