package Negocio.UbicacionGeografica;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TBarrios generated by hbm2java
 */
@Entity
@Table(name="T_BARRIOS"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class Barrio  implements java.io.Serializable {


     private short idBarrio;
     private Localidad TLocalidades;
     private String nombre;
     private String descripcion;
     

    public Barrio() {
    }

	
    public Barrio(short idBarrio, Localidad TLocalidades, String nombre) {
        this.idBarrio = idBarrio;
        this.TLocalidades = TLocalidades;
        this.nombre = nombre;
    }
    public Barrio(short idBarrio, Localidad TLocalidades, String nombre, String descripcion) {
       this.idBarrio = idBarrio;
       this.TLocalidades = TLocalidades;
       this.nombre = nombre;
       this.descripcion = descripcion;
       
    }
   
     @Id 
    
    @Column(name="ID_BARRIO", unique=true, nullable=false, precision=3, scale=0)
    public short getIdBarrio() {
        return this.idBarrio;
    }
    
    public void setIdBarrio(short idBarrio) {
        this.idBarrio = idBarrio;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_LOCALIDAD", nullable=false)
    public Localidad getTLocalidades() {
        return this.TLocalidades;
    }
    
    public void setTLocalidades(Localidad TLocalidades) {
        this.TLocalidades = TLocalidades;
    }
    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="DESCRIPCION", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String toString(){
        return this.getNombre();
    }

}


