package Negocio.UbicacionGeografica;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TProvincias generated by hbm2java
 */
@Entity
@Table(name="T_PROVINCIAS"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class Provincia  implements java.io.Serializable {


     private int idProvincia;
     private Pais TPaises;
     private String nombre;
     private String descripcion;
     private Set<Localidad> TLocalidadeses = new HashSet<Localidad>(0);
    

    public Provincia() {
    }

	
    public Provincia(int idProvincia, Pais TPaises, String nombre) {
        this.idProvincia = idProvincia;
        this.TPaises = TPaises;
        this.nombre = nombre;
    }
    public Provincia(int idProvincia, Pais TPaises, String nombre, String descripcion, Set<Localidad> TLocalidadeses ) {
       this.idProvincia = idProvincia;
       this.TPaises = TPaises;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.TLocalidadeses = TLocalidadeses;
       
    }
   
     @Id 
    
    @Column(name="ID_PROVINCIA", unique=true, nullable=false, precision=5, scale=0)
    public int getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(int idProvincia) {
        this.idProvincia = idProvincia;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PAIS", nullable=false)
    public Pais getTPaises() {
        return this.TPaises;
    }
    
    public void setTPaises(Pais TPaises) {
        this.TPaises = TPaises;
    }
    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="DESCRIPCION", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TProvincias")
    public Set<Localidad> getTLocalidadeses() {
        return this.TLocalidadeses;
    }
    
    public void setTLocalidadeses(Set<Localidad> TLocalidadeses) {
        this.TLocalidadeses = TLocalidadeses;
    }





}


