package Negocio.Administracion;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import Negocio.Administracion.Factura;
import Negocio.Ventas.DetallePedido;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TDetallesFactura generated by hbm2java
 */
@Entity
@Table(name="T_DETALLES_FACTURA"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class DetalleFactura  implements java.io.Serializable {


     private int idDetalleFactura;
     private Factura TFacturas;
     private DetallePedido TDetallesPedido;
     private int cantidad;
     private BigDecimal precio;

    public DetalleFactura() {
    }

    public DetalleFactura(int idDetalleFactura, Factura TFacturas, DetallePedido TDetallesPedido, int cantidad, BigDecimal precio) {
       this.idDetalleFactura = idDetalleFactura;
       this.TFacturas = TFacturas;
       this.TDetallesPedido = TDetallesPedido;
       this.cantidad = cantidad;
       this.precio = precio;
    }
   
     @Id 
    
    @Column(name="ID_DETALLE_FACTURA", unique=true, nullable=false, precision=8, scale=0)
    public int getIdDetalleFactura() {
        return this.idDetalleFactura;
    }
    
    public void setIdDetalleFactura(int idDetalleFactura) {
        this.idDetalleFactura = idDetalleFactura;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_FACTURA", nullable=false)
    public Factura getTFacturas() {
        return this.TFacturas;
    }
    
    public void setTFacturas(Factura TFacturas) {
        this.TFacturas = TFacturas;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_DETALLE_PEDIDO", nullable=false)
    public DetallePedido getTDetallesPedido() {
        return this.TDetallesPedido;
    }
    
    public void setTDetallesPedido(DetallePedido TDetallesPedido) {
        this.TDetallesPedido = TDetallesPedido;
    }
    
    @Column(name="CANTIDAD", nullable=false, precision=5, scale=0)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    
    @Column(name="PRECIO", nullable=false, precision=6)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }




}


