package Negocio.Administracion;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TDiasHoraLaborable generated by hbm2java
 */
@Entity
@Table(name="T_DIAS_HORA_LABORABLE"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class DiaHoraLaborable  implements java.io.Serializable {


     private short idDiaHoraLaborable;
     private Empleado TEmpleados;
     private String dia;
     private String horaInicio;
     private String horaFin;

    public DiaHoraLaborable() {
    }

	
    public DiaHoraLaborable(short idDiaHoraLaborable, Empleado TEmpleados, String dia, String horaInicio) {
        this.idDiaHoraLaborable = idDiaHoraLaborable;
        this.TEmpleados = TEmpleados;
        this.dia = dia;
        this.horaInicio = horaInicio;
    }
    public DiaHoraLaborable(short idDiaHoraLaborable, Empleado TEmpleados, String dia, String horaInicio, String horaFin) {
       this.idDiaHoraLaborable = idDiaHoraLaborable;
       this.TEmpleados = TEmpleados;
       this.dia = dia;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
    }
   
     @Id 
    
    @Column(name="ID_DIA_HORA_LABORABLE", unique=true, nullable=false, precision=4, scale=0)
    public short getIdDiaHoraLaborable() {
        return this.idDiaHoraLaborable;
    }
    
    public void setIdDiaHoraLaborable(short idDiaHoraLaborable) {
        this.idDiaHoraLaborable = idDiaHoraLaborable;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_EMPLEADO", nullable=false)
    public Empleado getTEmpleados() {
        return this.TEmpleados;
    }
    
    public void setTEmpleados(Empleado TEmpleados) {
        this.TEmpleados = TEmpleados;
    }
    
    @Column(name="DIA", nullable=false, length=20)
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    
    @Column(name="HORA_INICIO", nullable=false, length=20)
    public String getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(String horaInicio) {
        this.horaInicio = horaInicio;
    }
    
    @Column(name="HORA_FIN", length=20)
    public String getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(String horaFin) {
        this.horaFin = horaFin;
    }




}


