package Negocio.Administracion;
// Generated 21/10/2011 13:42:06 by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * THorarios generated by hbm2java
 */
@Entity
@Table(name="T_HORARIOS"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class Horarios  implements java.io.Serializable {


     private byte idHorario;
     /*---------------------------------------------------------------------------------------------*/
     private Serializable nombre;
     /*---------------------------------------------------------------------------------------------*/
     private String descripcion;
     /*---------------------------------------------------------------------------------------------*/
     private Set TAsignacionesDiases = new HashSet(0);
     /*---------------------------------------------------------------------------------------------*/
//     private Set TAsignacionesHorarios = new HashSet(0);
     /*---------------------------------------------------------------------------------------------*/

    public Horarios() {
    }

	
    public Horarios(byte idHorario, Serializable nombre) {
        this.idHorario = idHorario;
        this.nombre = nombre;
    }
    public Horarios(byte idHorario, Serializable nombre, String descripcion, Set TAsignacionesDiases, Set TAsignacionesHorarios) {
       this.idHorario = idHorario;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.TAsignacionesDiases = TAsignacionesDiases;
//       this.TAsignacionesHorarios = TAsignacionesHorarios;
    }
   
     @Id 
    @GeneratedValue
    @Column(name="ID_HORARIO", unique=true, nullable=false, precision=2, scale=0)
    public byte getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(byte idHorario) {
        this.idHorario = idHorario;
    }
    
    @Column(name="NOMBRE", nullable=false)
    public Serializable getNombre() {
        return this.nombre;
    }
    
    public void setNombre(Serializable nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="DESCRIPCION", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="THorarios")
    public Set getTAsignacionesDiases() {
        return this.TAsignacionesDiases;
    }
    
    public void setTAsignacionesDiases(Set TAsignacionesDiases) {
        this.TAsignacionesDiases = TAsignacionesDiases;
    }
//@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="THorarios")
//    public Set getTAsignacionesHorarios() {
//        return this.TAsignacionesHorarios;
//    }
//
//    public void setTAsignacionesHorarios(Set TAsignacionesHorarios) {
//        this.TAsignacionesHorarios = TAsignacionesHorarios;
//    }


}


