
import Presentacion.Utilidades;
import Presentacion.ValidarTexbox;
import java.awt.Color;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Prueba.java
 *
 * Created on 12/07/2011, 11:11:19
 */

/**
 *
 * @author Gabriela
 */
public class Prueba extends javax.swing.JFrame {

    /** Creates new form Prueba */
    public Prueba() {
        initComponents();
        ValidarTexbox.validarInt(txt1);
        Utilidades.componenteCorrecto(ff);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt1 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        txt2 = new javax.swing.JTextField();
        txt22 = new javax.swing.JTextField();
        ff = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt1KeyTyped(evt);
            }
        });

        btn1.setText("jButton1");

        txt22.setText("jTextField1");

        ff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ffMouseClicked(evt);
            }
        });
        ff.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ffFocusLost(evt);
            }
        });
        ff.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ffPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addComponent(txt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btn1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(ff, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1))
                .addGap(18, 18, 18)
                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(ff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(277, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt1KeyPressed

    private void txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txt1KeyTyped

    private void ffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ffMouseClicked
        // TODO add your handling code here:

        //  txtFechaEstimada.setText(Utilidades.parseFecha(dtcFechaNacimiento.getDate()));
}//GEN-LAST:event_ffMouseClicked

    private void ffFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ffFocusLost
        // TODO add your handling code here:
//        if(empleado!=null) {
//            try{
//                empleado.setFecNacimiento(dtcFechaNacimiento.getDate());
//                Utilidades.componenteCorrecto(dtcFechaNacimiento);
//            }catch(TipoDatoException ex){
//                dtcFechaNacimiento.setToolTipText(ex.getMessage());
//                Utilidades.componenteError(dtcFechaNacimiento);
//            }
//        }
}//GEN-LAST:event_ffFocusLost

    private void ffPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ffPropertyChange
        // TODO add your handling code here:
//        if(empleado!=null) {
//            try{
//                empleado.setFecNacimiento(dtcFechaNacimiento.getDate());
//                Utilidades.componenteCorrecto(dtcFechaNacimiento);
//            }catch(TipoDatoException ex){
//                dtcFechaNacimiento.setToolTipText(ex.getMessage());
//                Utilidades.componenteError(dtcFechaNacimiento);
//            }
//        }
}//GEN-LAST:event_ffPropertyChange

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private com.toedter.calendar.JDateChooser ff;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt22;
    // End of variables declaration//GEN-END:variables

}
