package BaseDeDatos.Deposito;
// Generated 09/08/2011 13:12:12 by Hibernate Tools 3.2.1.GA


import BaseDeDatos.Produccion.TDetallesPlan;
import BaseDeDatos.Compras.TDetallesOrdenCompra;
import BaseDeDatos.Compras.TMateriales;
import java.math.BigDecimal;
import java.util.Date;

/**
 * TFaltantes generated by hbm2java
 */
public class TFaltantes  implements java.io.Serializable {


     private short idFaltante;
     private TDetallesPlan TDetallesPlan;
     private TDetallesOrdenCompra TDetallesOrdenCompra;
     private TMateriales TMateriales;
     private BigDecimal cantidad;
     private Date fecGeneracion;
     private Date fecNecesidad;

    public TFaltantes() {
    }

	
    public TFaltantes(short idFaltante, TMateriales TMateriales, BigDecimal cantidad, Date fecGeneracion, Date fecNecesidad) {
        this.idFaltante = idFaltante;
        this.TMateriales = TMateriales;
        this.cantidad = cantidad;
        this.fecGeneracion = fecGeneracion;
        this.fecNecesidad = fecNecesidad;
    }
    public TFaltantes(short idFaltante, TDetallesPlan TDetallesPlan, TDetallesOrdenCompra TDetallesOrdenCompra, TMateriales TMateriales, BigDecimal cantidad, Date fecGeneracion, Date fecNecesidad) {
       this.idFaltante = idFaltante;
       this.TDetallesPlan = TDetallesPlan;
       this.TDetallesOrdenCompra = TDetallesOrdenCompra;
       this.TMateriales = TMateriales;
       this.cantidad = cantidad;
       this.fecGeneracion = fecGeneracion;
       this.fecNecesidad = fecNecesidad;
    }
   
    public short getIdFaltante() {
        return this.idFaltante;
    }
    
    public void setIdFaltante(short idFaltante) {
        this.idFaltante = idFaltante;
    }
    public TDetallesPlan getTDetallesPlan() {
        return this.TDetallesPlan;
    }
    
    public void setTDetallesPlan(TDetallesPlan TDetallesPlan) {
        this.TDetallesPlan = TDetallesPlan;
    }
    public TDetallesOrdenCompra getTDetallesOrdenCompra() {
        return this.TDetallesOrdenCompra;
    }
    
    public void setTDetallesOrdenCompra(TDetallesOrdenCompra TDetallesOrdenCompra) {
        this.TDetallesOrdenCompra = TDetallesOrdenCompra;
    }
    public TMateriales getTMateriales() {
        return this.TMateriales;
    }
    
    public void setTMateriales(TMateriales TMateriales) {
        this.TMateriales = TMateriales;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFecGeneracion() {
        return this.fecGeneracion;
    }
    
    public void setFecGeneracion(Date fecGeneracion) {
        this.fecGeneracion = fecGeneracion;
    }
    public Date getFecNecesidad() {
        return this.fecNecesidad;
    }
    
    public void setFecNecesidad(Date fecNecesidad) {
        this.fecNecesidad = fecNecesidad;
    }




}


