package Negocio.GestionUsuario;
// Generated 12/08/2011 13:27:23 by Hibernate Tools 3.2.1.GA


import Negocio.Administracion.Empleado;
import Negocio.Ventas.Cliente;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;

/**
 * TUsuarios generated by hbm2java
 */
@Entity
@Table(name="T_USUARIOS"
    ,schema="dbo"
    ,catalog="Ramaty"
)
public class Usuario  implements java.io.Serializable {

    
    @Id    
    @Column(name="ID_USUARIO", unique=true, nullable=false, precision=5, scale=0)
     private int idUsuario;
    @Column(name="NOMBRE_USUARIO", nullable=false, length=50)
     private String nombreUsuario;
    @Column(name="CONTRASENIA", nullable=false, length=50)
     private String contrasenia;
    
//    @ManyToOne(fetch=FetchType.LAZY)
//    @JoinColumn(name="ID_USUARIO", nullable=false)
//    private Empleado TEmpleado = null;
    
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USUARIO", nullable=false)
     private Set<RolXUsuario> TRolXUsuario = new HashSet<RolXUsuario>(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String nombreUsuario, String contrasenia) {
        this.idUsuario = idUsuario;
        this.nombreUsuario = nombreUsuario;
        this.contrasenia = contrasenia;
    }
   
    public Usuario(int idUsuario, String nombreUsuario, String contrasenia, Set<RolXUsuario> TRolXUsuario) {
       this.idUsuario = idUsuario;
       this.nombreUsuario = nombreUsuario;
       this.contrasenia = contrasenia;
//       this.TEmpleado = TEmpleado;
       this.TRolXUsuario = TRolXUsuario;
    }

    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    
    
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    
    
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

//    public Empleado getTEmpleadoses() {
//        return this.TEmpleado;
//    }
//    
//    public void setTEmpleadoses(Empleado TEmpleado) {
//        this.TEmpleado = TEmpleado;
//    }

    public Set<RolXUsuario> getTRolXUsuario() {
        return TRolXUsuario;
    }

    
    public void setTRolXUsuario(Set<RolXUsuario> TRolXUsuario) {
        this.TRolXUsuario = TRolXUsuario;
    }
}


